// MARK: - Infrastructure Generator
// Generates StripeClient.swift — the auto-wired client that connects all route structs.
// All other infrastructure files (StripeError, StripeEvent, StripeAPIHandler, etc.)
// are hand-written in Sources/StripeKit/Infrastructure/ and are never regenerated.

import Foundation

struct InfraGenerator {
    let spec: OpenAPISpec
    let parser: SpecParser
    let resources: [StripeResource]
    let pathMapping: [String: [(method: String, path: String)]]
    
    // MARK: - StripeClient
    
    /// Generate the StripeClient struct that wires all route structs
    func generateStripeClient() -> String {
        var lines: [String] = []
        
        // Collect resources that have routes
        let routeGen = RouteGenerator(spec: spec, parser: parser, pathMapping: pathMapping)
        let routedResources = resources.filter { routeGen.generate(resource: $0) != nil }
        
        lines.append("//")
        lines.append("//  StripeClient.swift")
        lines.append("//  StripeKit")
        lines.append("//")
        lines.append("//  Generated by stripe-kit-codegen")
        lines.append("//  API Version: \(spec.info.version)")
        lines.append("//")
        lines.append("")
        lines.append("import Foundation")
        lines.append("import AsyncHTTPClient")
        lines.append("import NIO")
        lines.append("import NIOHTTP1")
        lines.append("")
        
        // Client struct
        lines.append("/// The entry point for the Stripe API.")
        lines.append("/// API Version: \(spec.info.version)")
        lines.append("public struct StripeClient: Sendable {")
        lines.append("    /// The API handler used for requests. Stored to support `onBehalfOf()` scoping.")
        lines.append("    public let handler: StripeAPIHandler")
        lines.append("")
        
        for resource in routedResources {
            let propName = clientPropertyName(resource)
            lines.append("    public var \(propName): \(resource.swiftTypeName)Routes")
        }
        
        lines.append("}")
        lines.append("")
        
        // .live factory
        lines.append("extension StripeClient {")
        lines.append("    /// Create a live client connected to the Stripe API.")
        lines.append("    public static func live(httpClient: HTTPClient, apiKey: String, stripeAccount: String? = nil, idempotencyKey: String? = nil) -> StripeClient {")
        lines.append("        let handler = StripeAPIHandler(httpClient: httpClient, apiKey: apiKey, stripeAccount: stripeAccount, idempotencyKey: idempotencyKey)")
        lines.append("        return StripeClient(")
        lines.append("            handler: handler,")
        
        for (idx, resource) in routedResources.enumerated() {
            let propName = clientPropertyName(resource)
            let comma = idx < routedResources.count - 1 ? "," : ""
            lines.append("            \(propName): \(resource.swiftTypeName)Routes.live(handler: handler)\(comma)")
        }
        
        lines.append("        )")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        return lines.joined(separator: "\n")
    }
    
    // MARK: - StripeEventType
    
    /// Generate the StripeEventType enum from the spec's event.type enum values
    func generateEventType() -> String {
        var lines: [String] = []
        
        lines.append("//")
        lines.append("//  StripeEventType.swift")
        lines.append("//  StripeKit")
        lines.append("//")
        lines.append("//  Generated by stripe-kit-codegen")
        lines.append("//")
        lines.append("")
        lines.append("import Foundation")
        lines.append("")
        lines.append("/// The type of a Stripe webhook event.")
        lines.append("/// Generated from the OpenAPI spec's `event.type` enum values.")
        lines.append("public enum StripeEventType: String, Codable, Sendable {")
        
        // Extract enum cases from the event schema's type property
        if let eventSchema = spec.components.schemas["event"],
           let typeProperty = eventSchema.properties?["type"],
           let enumCases = typeProperty.enum {
            for rawValue in enumCases.sorted() {
                let caseName = enumCaseToSwift(rawValue)
                lines.append("    case \(caseName) = \"\(rawValue)\"")
            }
        }
        
        lines.append("")
        lines.append("    /// An event type not yet known to this version of StripeKit.")
        lines.append("    case unknown")
        lines.append("")
        lines.append("    public init(from decoder: Decoder) throws {")
        lines.append("        let container = try decoder.singleValueContainer()")
        lines.append("        let rawValue = try container.decode(String.self)")
        lines.append("        self = Self(rawValue: rawValue) ?? .unknown")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        
        return lines.joined(separator: "\n")
    }
    
    // MARK: - StripeEvent
    
    /// Generate the StripeEvent struct from the spec's event schema
    func generateStripeEvent() -> String {
        var lines: [String] = []
        
        lines.append("//")
        lines.append("//  StripeEvent.swift")
        lines.append("//  StripeKit")
        lines.append("//")
        lines.append("//  Generated by stripe-kit-codegen")
        lines.append("//")
        lines.append("")
        lines.append("import Foundation")
        lines.append("import Crypto")
        lines.append("")
        
        // Build property list from the event schema
        guard let eventSchema = spec.components.schemas["event"] else {
            fatalError("Missing 'event' schema in spec")
        }
        
        let required = Set(eventSchema.required ?? [])
        let properties = eventSchema.properties ?? [:]
        
        // Map spec properties to Swift declarations
        struct EventProperty: Comparable {
            let specName: String
            let swiftName: String
            let swiftType: String
            let isOptional: Bool
            let needsCodingKey: Bool // true if specName != swiftName
            
            static func < (lhs: EventProperty, rhs: EventProperty) -> Bool {
                lhs.specName < rhs.specName
            }
        }
        
        var eventProps: [EventProperty] = []
        
        for (name, prop) in properties {
            let swiftName = snakeToCamel(name)
            let isRequired = required.contains(name)
            let isNullable = prop.nullable ?? false
            let isOptional = !isRequired || isNullable
            
            // Determine Swift type
            let baseType: String
            switch name {
            case "type":
                baseType = "StripeEventType"
            case "data":
                baseType = "EventData"
            case "request":
                baseType = "EventRequest"
            case "created":
                baseType = "Date"
            default:
                switch prop.type {
                case "string": baseType = "String"
                case "integer": baseType = "Int"
                case "boolean": baseType = "Bool"
                default: baseType = "String"
                }
            }
            
            let swiftType = isOptional ? "\(baseType)?" : baseType
            let needsCodingKey = swiftName != name
            
            eventProps.append(EventProperty(
                specName: name,
                swiftName: swiftName,
                swiftType: swiftType,
                isOptional: isOptional,
                needsCodingKey: needsCodingKey
            ))
        }
        
        eventProps.sort()
        
        // StripeEvent struct
        lines.append("/// A Stripe webhook event with typed event type and object extraction.")
        lines.append("/// Generated from the OpenAPI spec's `event` schema.")
        lines.append("public struct StripeEvent: Codable, Sendable {")
        
        for prop in eventProps {
            lines.append("    public var \(prop.swiftName): \(prop.swiftType)")
        }
        
        // CodingKeys — only needed if any property has a different spec name
        let propsNeedingCodingKey = eventProps.filter { $0.needsCodingKey }
        if !propsNeedingCodingKey.isEmpty {
            lines.append("")
            lines.append("    public enum CodingKeys: String, CodingKey {")
            
            // Emit all properties, with explicit raw values only for those that differ
            for prop in eventProps {
                if prop.needsCodingKey {
                    lines.append("        case \(prop.swiftName) = \"\(prop.specName)\"")
                } else {
                    lines.append("        case \(prop.swiftName)")
                }
            }
            
            lines.append("    }")
        }
        
        lines.append("}")
        lines.append("")
        
        // EventData — custom infrastructure (not from spec)
        lines.append("public struct EventData: Codable, Sendable {")
        lines.append("    /// The raw JSON object. Use `object(as:)` for typed access.")
        lines.append("    public var _object: AnyCodableValue?")
        lines.append("    /// The raw JSON previous attributes. Use `previousAttributes(as:)` for typed access.")
        lines.append("    public var _previousAttributes: AnyCodableValue?")
        lines.append("")
        lines.append("    public enum CodingKeys: String, CodingKey {")
        lines.append("        case _object = \"object\"")
        lines.append("        case _previousAttributes = \"previous_attributes\"")
        lines.append("    }")
        lines.append("")
        lines.append("    /// Decode the event's object as a typed Stripe resource.")
        lines.append("    public func object<T: Codable>(as type: T.Type) throws -> T {")
        lines.append("        let data = try JSONSerialization.data(withJSONObject: _object?.value ?? [:] as [String: Any])")
        lines.append("        let decoder = JSONDecoder()")
        lines.append("        decoder.dateDecodingStrategy = .secondsSince1970")
        lines.append("        decoder.keyDecodingStrategy = .convertFromSnakeCase")
        lines.append("        return try decoder.decode(T.self, from: data)")
        lines.append("    }")
        lines.append("")
        lines.append("    /// Decode the event's previous attributes as a Stripe resource.")
        lines.append("    /// Only changed fields are present — non-optional model fields that were")
        lines.append("    /// unchanged will decode as nil since they aren't in the JSON.")
        lines.append("    public func previousAttributes<T: Codable>(as type: T.Type) throws -> T? {")
        lines.append("        guard let prev = _previousAttributes?.value else { return nil }")
        lines.append("        let data = try JSONSerialization.data(withJSONObject: prev)")
        lines.append("        let decoder = JSONDecoder()")
        lines.append("        decoder.dateDecodingStrategy = .secondsSince1970")
        lines.append("        decoder.keyDecodingStrategy = .convertFromSnakeCase")
        lines.append("        return try decoder.decode(T.self, from: data)")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        
        // EventRequest
        lines.append("public struct EventRequest: Codable, Sendable {")
        lines.append("    public var id: String?")
        lines.append("    public var idempotencyKey: String?")
        lines.append("")
        lines.append("    public enum CodingKeys: String, CodingKey {")
        lines.append("        case id")
        lines.append("        case idempotencyKey = \"idempotency_key\"")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        
        // Signature Verification
        lines.append("// MARK: - Signature Verification")
        lines.append("")
        lines.append("extension StripeEvent {")
        lines.append("    /// Verify a webhook signature and decode the event.")
        lines.append("    /// - Parameters:")
        lines.append("    ///   - payload: The raw request body bytes")
        lines.append("    ///   - header: The Stripe-Signature header value")
        lines.append("    ///   - secret: Your webhook endpoint secret (whsec_...)")
        lines.append("    ///   - tolerance: Maximum age in seconds (default: 300)")
        lines.append("    /// - Returns: The decoded and verified StripeEvent")
        lines.append("    public static func verify(")
        lines.append("        payload: Data,")
        lines.append("        header: String,")
        lines.append("        secret: String,")
        lines.append("        tolerance: Double = 300")
        lines.append("    ) throws -> StripeEvent {")
        lines.append("        try verifySignature(payload: payload, header: header, secret: secret, tolerance: tolerance)")
        lines.append("")
        lines.append("        // Decode the event")
        lines.append("        let decoder = JSONDecoder()")
        lines.append("        decoder.dateDecodingStrategy = .secondsSince1970")
        lines.append("        decoder.keyDecodingStrategy = .convertFromSnakeCase")
        lines.append("        return try decoder.decode(StripeEvent.self, from: payload)")
        lines.append("    }")
        lines.append("")
        lines.append("    /// Verify a webhook signature without decoding the event.")
        lines.append("    /// Throws if the signature is invalid, the header is malformed, or the timestamp is too old.")
        lines.append("    public static func verifySignature(")
        lines.append("        payload: Data,")
        lines.append("        header: String,")
        lines.append("        secret: String,")
        lines.append("        tolerance: Double = 300")
        lines.append("    ) throws {")
        lines.append("        // Parse header: t=timestamp,v1=sig1,v1=sig2,...")
        lines.append("        let pairs = header.split(separator: \",\").reduce(into: [String: [String]]()) { result, pair in")
        lines.append("            let kv = pair.split(separator: \"=\", maxSplits: 1)")
        lines.append("            guard kv.count == 2 else { return }")
        lines.append("            result[String(kv[0]), default: []].append(String(kv[1]))")
        lines.append("        }")
        lines.append("")
        lines.append("        guard let timestamps = pairs[\"t\"], let timestamp = timestamps.first,")
        lines.append("              let signatures = pairs[\"v1\"], !signatures.isEmpty")
        lines.append("        else { throw StripeSignatureError.unableToParseHeader }")
        lines.append("")
        lines.append("        // Compute expected signature")
        lines.append("        let signedPayload = \"\\(timestamp).\\(String(data: payload, encoding: .utf8) ?? \"\")\"")
        lines.append("        let secretKey = SymmetricKey(data: Data(secret.utf8))")
        lines.append("        let signature = HMAC<SHA256>.authenticationCode(for: Data(signedPayload.utf8), using: secretKey)")
        lines.append("        let expected = signature.map { String(format: \"%02x\", $0) }.joined()")
        lines.append("")
        lines.append("        // Check for a matching signature")
        lines.append("        guard signatures.contains(where: { $0 == expected }) else {")
        lines.append("            throw StripeSignatureError.noMatchingSignatureFound")
        lines.append("        }")
        lines.append("")
        lines.append("        // Verify timestamp tolerance")
        lines.append("        if let ts = Double(timestamp) {")
        lines.append("            let age = Date().timeIntervalSince1970 - ts")
        lines.append("            guard abs(age) <= tolerance else {")
        lines.append("                throw StripeSignatureError.timestampNotTolerated")
        lines.append("            }")
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        
        // AnyCodableValue
        lines.append("// MARK: - AnyCodableValue")
        lines.append("")
        lines.append("/// A type-erased Codable value for preserving raw JSON in webhook events.")
        lines.append("public struct AnyCodableValue: Codable, @unchecked Sendable {")
        lines.append("    public let value: Any")
        lines.append("")
        lines.append("    public init(_ value: Any) {")
        lines.append("        self.value = value")
        lines.append("    }")
        lines.append("")
        lines.append("    public init(from decoder: Decoder) throws {")
        lines.append("        let container = try decoder.singleValueContainer()")
        lines.append("        if container.decodeNil() {")
        lines.append("            value = Optional<Any>.none as Any")
        lines.append("        } else if let dict = try? container.decode([String: AnyCodableValue].self) {")
        lines.append("            value = dict.mapValues { $0.value }")
        lines.append("        } else if let array = try? container.decode([AnyCodableValue].self) {")
        lines.append("            value = array.map { $0.value }")
        lines.append("        } else if let string = try? container.decode(String.self) {")
        lines.append("            value = string")
        lines.append("        } else if let int = try? container.decode(Int.self) {")
        lines.append("            value = int")
        lines.append("        } else if let double = try? container.decode(Double.self) {")
        lines.append("            value = double")
        lines.append("        } else if let bool = try? container.decode(Bool.self) {")
        lines.append("            value = bool")
        lines.append("        } else {")
        lines.append("            value = Optional<Any>.none as Any")
        lines.append("        }")
        lines.append("    }")
        lines.append("")
        lines.append("    public func encode(to encoder: Encoder) throws {")
        lines.append("        var container = encoder.singleValueContainer()")
        lines.append("        switch value {")
        lines.append("        case let v as String: try container.encode(v)")
        lines.append("        case let v as Int: try container.encode(v)")
        lines.append("        case let v as Double: try container.encode(v)")
        lines.append("        case let v as Bool: try container.encode(v)")
        lines.append("        case let v as [Any]: try container.encode(v.map { AnyCodableValue($0) })")
        lines.append("        case let v as [String: Any]: try container.encode(v.mapValues { AnyCodableValue($0) })")
        lines.append("        default: try container.encodeNil()")
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        
        return lines.joined(separator: "\n")
    }
    
    // MARK: - Helpers
    
    private func clientPropertyName(_ resource: StripeResource) -> String {
        // PaymentIntent → paymentIntents (pluralized, camelCase)
        let typeName = resource.swiftTypeName
        let firstChar = typeName.prefix(1).lowercased()
        let rest = typeName.dropFirst()
        let camel = firstChar + rest
        
        // Pluralize
        if camel.hasSuffix("s") { return camel }
        if camel.hasSuffix("y") { return String(camel.dropLast()) + "ies" }
        return camel + "s"
    }
}
