// MARK: - Infrastructure Generator
// Generates StripeClient.swift — the auto-wired client that connects all route structs.
// All other infrastructure files (StripeError, StripeEvent, StripeAPIHandler, etc.)
// are hand-written in Sources/StripeKit/Infrastructure/ and are never regenerated.

import Foundation

struct InfraGenerator {
    let spec: OpenAPISpec
    let parser: SpecParser
    let resources: [StripeResource]
    let pathMapping: [String: [(method: String, path: String)]]
    
    // MARK: - StripeClient
    
    /// Generate the StripeClient struct that wires all route structs
    func generateStripeClient() -> String {
        var lines: [String] = []
        
        // Collect resources that have routes
        let routeGen = RouteGenerator(spec: spec, parser: parser, pathMapping: pathMapping)
        let routedResources = resources.filter { routeGen.generate(resource: $0) != nil }
        
        lines.append("//")
        lines.append("//  StripeClient.swift")
        lines.append("//  StripeKit")
        lines.append("//")
        lines.append("//  Generated by stripe-kit-codegen")
        lines.append("//  API Version: \(spec.info.version)")
        lines.append("//")
        lines.append("")
        lines.append("import Foundation")
        lines.append("import AsyncHTTPClient")
        lines.append("import NIO")
        lines.append("import NIOHTTP1")
        lines.append("")
        
        // Client struct
        lines.append("/// The entry point for the Stripe API.")
        lines.append("/// API Version: \(spec.info.version)")
        lines.append("public struct StripeClient: Sendable {")
        lines.append("    /// The API handler used for requests. Stored to support `onBehalfOf()` scoping.")
        lines.append("    public let handler: StripeAPIHandler")
        lines.append("")
        
        for resource in routedResources {
            let propName = clientPropertyName(resource)
            lines.append("    public var \(propName): \(resource.swiftTypeName)Routes")
        }
        
        lines.append("}")
        lines.append("")
        
        // .live factory
        lines.append("extension StripeClient {")
        lines.append("    /// Create a live client connected to the Stripe API.")
        lines.append("    public static func live(httpClient: HTTPClient, apiKey: String, stripeAccount: String? = nil, idempotencyKey: String? = nil) -> StripeClient {")
        lines.append("        let handler = StripeAPIHandler(httpClient: httpClient, apiKey: apiKey, stripeAccount: stripeAccount, idempotencyKey: idempotencyKey)")
        lines.append("        return StripeClient(")
        lines.append("            handler: handler,")
        
        for (idx, resource) in routedResources.enumerated() {
            let propName = clientPropertyName(resource)
            let comma = idx < routedResources.count - 1 ? "," : ""
            lines.append("            \(propName): \(resource.swiftTypeName)Routes.live(handler: handler)\(comma)")
        }
        
        lines.append("        )")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        return lines.joined(separator: "\n")
    }
    
    // MARK: - Helpers
    
    private func clientPropertyName(_ resource: StripeResource) -> String {
        // PaymentIntent → paymentIntents (pluralized, camelCase)
        let typeName = resource.swiftTypeName
        let firstChar = typeName.prefix(1).lowercased()
        let rest = typeName.dropFirst()
        let camel = firstChar + rest
        
        // Pluralize
        if camel.hasSuffix("s") { return camel }
        if camel.hasSuffix("y") { return String(camel.dropLast()) + "ies" }
        return camel + "s"
    }
}
