// MARK: - Model Generator
// Generates Swift model files from StripeResource intermediate representations
// Follows spec-driven optionality matching official Stripe TypeScript SDK:
//   - required + non-nullable → non-optional (guaranteed by Stripe)
//   - required + nullable → optional (Type?)
//   - not required → optional (Type?)

import Foundation

struct ModelGenerator {
    let allSchemas: [String: SchemaObject]
    
    /// Generate the full Swift source for a resource's model file
    func generate(resource: StripeResource) -> String {
        // Polymorphic anyOf schemas → generate enum instead of struct
        if let variants = resource.anyOfVariants, !variants.isEmpty {
            return generatePolymorphicEnum(resource: resource, variants: variants)
        }
        
        var lines: [String] = []
        
        // File header
        lines.append("//")
        lines.append("//  \(resource.swiftTypeName).swift")
        lines.append("//  StripeKit")
        lines.append("//")
        lines.append("//  Generated by stripe-kit-codegen")
        lines.append("//")
        lines.append("")
        lines.append("import Foundation")
        lines.append("")
        
        // Doc comment
        if !resource.description.isEmpty {
            let cleaned = cleanDescription(resource.description)
            let wrapped = wordWrap(cleaned, lineLength: 100)
            for line in wrapped {
                lines.append("/// \(line)")
            }
        }
        
        // Struct declaration
        lines.append("public struct \(resource.swiftTypeName): Codable, Sendable {")
        
        // Properties
        for property in resource.properties {
            lines.append(contentsOf: generateProperty(property, resource: resource))
        }
        
        // CodingKeys enum if any property names differ from swift names
        let needsCodingKeys = resource.properties.contains { $0.name != $0.swiftName }
        if needsCodingKeys {
            lines.append("")
            lines.append("    public enum CodingKeys: String, CodingKey {")
            for property in resource.properties {
                if property.name != property.swiftName {
                    lines.append("        case \(escapedSwiftName(property.swiftName)) = \"\(property.name)\"")
                } else {
                    lines.append("        case \(escapedSwiftName(property.swiftName))")
                }
            }
            lines.append("    }")
        }
        
        lines.append("}")
        lines.append("")
        
        // Generate standalone enum types for enum-typed properties
        for property in resource.properties {
            if case .enum(let cases) = property.type, !cases.isEmpty {
                let filtered = cases.filter { !$0.isEmpty }
                guard !filtered.isEmpty else { continue }
                let enumName = "\(resource.swiftTypeName)\(capitalize(property.swiftName))"
                lines.append(contentsOf: generateEnum(
                    name: enumName,
                    cases: filtered,
                    description: property.description
                ))
                lines.append("")
            }
        }
        
        // Generate List type
        lines.append(contentsOf: generateListType(resource: resource))
        lines.append("")
        
        return lines.joined(separator: "\n")
    }
    
    // MARK: - Property Generation
    
    private func generateProperty(_ property: StripeProperty, resource: StripeResource) -> [String] {
        var lines: [String] = []
        
        // Doc comment for the property
        if !property.description.isEmpty {
            let cleaned = cleanDescription(property.description)
            let wrapped = wordWrap(cleaned, lineLength: 100)
            for line in wrapped {
                lines.append("    /// \(line)")
            }
        }
        
        // Spec-driven optionality (matching TypeScript SDK):
        //   required + non-nullable → non-optional
        //   required + nullable → optional
        //   not-required → optional
        let isNonOptional = property.isRequired && !property.isNullable
        // Expandable properties are always optional — the wrapper's wrappedValue is String?/[String]?
        let isExpandableType: Bool
        switch property.type {
        case .expandable, .dynamicExpandable, .expandableCollection: isExpandableType = true
        default: isExpandableType = false
        }
        let optionalMark = (isNonOptional && !isExpandableType) ? "" : "?"
        
        // Expandable property wrapper annotations
        // Filter out Deleted* types (not generated) and cap DynamicExpandable at 2 type params
        switch property.type {
        case .expandable(let wrappedType):
            if !wrappedType.starts(with: "Deleted") {
                lines.append("    @Expandable<\(wrappedType)>")
            }
        case .dynamicExpandable(let types):
            let validTypes = types.filter { !$0.starts(with: "Deleted") }
            if let first = validTypes.first, validTypes.count == 1 {
                lines.append("    @Expandable<\(first)>")
            } else if validTypes.count == 2 {
                let typeList = validTypes.joined(separator: ", ")
                lines.append("    @DynamicExpandable<\(typeList)>")
            }
            // 0 or 3+ types: fall back to plain String (no annotation)
        case .expandableCollection(let wrappedType):
            if !wrappedType.starts(with: "Deleted") {
                lines.append("    @ExpandableCollection<\(wrappedType)>")
            }
        default:
            break
        }
        
        let swiftType = swiftTypeString(for: property, resource: resource)
        lines.append("    public var \(escapedSwiftName(property.swiftName)): \(swiftType)\(optionalMark)")
        
        return lines
    }
    
    // MARK: - Type Mapping
    
    func swiftTypeString(for property: StripeProperty, resource: StripeResource) -> String {
        typeToSwift(property.type, propertyName: property.swiftName, resourceName: resource.swiftTypeName)
    }
    
    func typeToSwift(_ type: StripePropertyType, propertyName: String = "", resourceName: String = "") -> String {
        switch type {
        case .string: return "String"
        case .integer: return "Int"
        case .number: return "Double"
        case .boolean: return "Bool"
        case .date: return "Date"
        case .object(let name): return name
        case .array(let element): return "[\(typeToSwift(element))]"
        case .dictionary(let value): return "[String: \(typeToSwift(value))]"
        case .expandable: return "String"
        case .dynamicExpandable: return "String"
        case .expandableCollection: return "[String]"
        case .enum:
            // Wire enum type: ResourceNamePropertyName
            if !resourceName.isEmpty && !propertyName.isEmpty {
                return "\(resourceName)\(capitalize(propertyName))"
            }
            return "String"
        case .hash: return "[String: String]"
        case .any: return "String"
        }
    }
    
    // MARK: - Enum Generation
    
    private func generateEnum(name: String, cases: [String], description: String) -> [String] {
        var lines: [String] = []
        
        if !description.isEmpty {
            let cleaned = cleanDescription(description)
            let wrapped = wordWrap(cleaned, lineLength: 100)
            for line in wrapped {
                lines.append("/// \(line)")
            }
        }
        lines.append("public enum \(name): String, Codable, Sendable {")
        for enumCase in cases {
            let swiftCase = enumCaseToSwift(enumCase)
            if swiftCase != enumCase {
                lines.append("    case \(swiftCase) = \"\(enumCase)\"")
            } else {
                lines.append("    case \(swiftCase)")
            }
        }
        lines.append("}")
        
        return lines
    }
    
    // MARK: - List Type Generation
    
    // MARK: - Polymorphic Enum Generation
    
    /// Generate a Swift enum for a polymorphic anyOf schema (e.g., external_account → BankAccount | Card)
    private func generatePolymorphicEnum(resource: StripeResource, variants: [String]) -> String {
        var lines: [String] = []
        
        // File header
        lines.append("//")
        lines.append("//  \(resource.swiftTypeName).swift")
        lines.append("//  StripeKit")
        lines.append("//")
        lines.append("//  Generated by stripe-kit-codegen")
        lines.append("//")
        lines.append("")
        lines.append("import Foundation")
        lines.append("")
        
        // Build variant info: (resourceId, swiftType, objectValue)
        let variantInfos = variants.map { resourceId -> (id: String, swiftType: String, caseName: String) in
            let swiftType = schemaIdToSwiftType(resourceId)
            let caseName = enumCaseToSwift(resourceId)
            return (id: resourceId, swiftType: swiftType, caseName: caseName)
        }
        
        lines.append("/// Polymorphic type — discriminated on the `object` field.")
        lines.append("/// Variants: \(variantInfos.map(\.swiftType).joined(separator: ", "))")
        lines.append("public enum \(resource.swiftTypeName): Codable, Sendable {")
        
        // Enum cases with associated values
        for v in variantInfos {
            lines.append("    case \(v.caseName)(\(v.swiftType))")
        }
        
        lines.append("")
        lines.append("    // MARK: - Discriminated Codable")
        lines.append("")
        lines.append("    private enum CodingKeys: String, CodingKey {")
        lines.append("        case object")
        lines.append("    }")
        lines.append("")
        
        // init(from:)
        lines.append("    public init(from decoder: Decoder) throws {")
        lines.append("        let container = try decoder.container(keyedBy: CodingKeys.self)")
        lines.append("        let object = try container.decode(String.self, forKey: .object)")
        lines.append("        switch object {")
        for v in variantInfos {
            lines.append("        case \"\(v.id)\":")
            lines.append("            self = .\(v.caseName)(try \(v.swiftType)(from: decoder))")
        }
        lines.append("        default:")
        lines.append("            throw DecodingError.dataCorrupted(")
        lines.append("                DecodingError.Context(")
        lines.append("                    codingPath: decoder.codingPath,")
        lines.append("                    debugDescription: \"Unknown \(resource.swiftTypeName) object type: \\(object)\"")
        lines.append("                )")
        lines.append("            )")
        lines.append("        }")
        lines.append("    }")
        lines.append("")
        
        // encode(to:)
        lines.append("    public func encode(to encoder: Encoder) throws {")
        lines.append("        switch self {")
        for v in variantInfos {
            lines.append("        case .\(v.caseName)(let value):")
            lines.append("            try value.encode(to: encoder)")
        }
        lines.append("        }")
        lines.append("    }")
        lines.append("")
        
        // Convenience accessors
        for v in variantInfos {
            lines.append("    /// Returns the \(v.swiftType) if this is a `.\(v.caseName)`, otherwise nil.")
            lines.append("    public var \(v.caseName): \(v.swiftType)? {")
            lines.append("        if case .\(v.caseName)(let value) = self { return value }")
            lines.append("        return nil")
            lines.append("    }")
            lines.append("")
        }
        
        lines.append("}")
        lines.append("")
        
        // Generate polymorphic list type
        lines.append(contentsOf: generatePolymorphicListType(resource: resource, variantInfos: variantInfos))
        lines.append("")
        
        return lines.joined(separator: "\n")
    }
    
    /// Generate a polymorphic list type that decodes items into typed arrays
    private func generatePolymorphicListType(
        resource: StripeResource,
        variantInfos: [(id: String, swiftType: String, caseName: String)]
    ) -> [String] {
        let listName = "\(resource.swiftTypeName)List"
        var lines: [String] = []
        
        lines.append("/// Polymorphic list — decodes items by `object` discriminator into typed arrays.")
        lines.append("public struct \(listName): Codable, Sendable {")
        lines.append("    public var object: String")
        lines.append("    public var hasMore: Bool?")
        lines.append("    public var url: String?")
        lines.append("")
        
        // Typed arrays for each variant
        for v in variantInfos {
            let pluralName = pluralPropertyName(v.caseName)
            lines.append("    /// \(v.swiftType) items in this list")
            lines.append("    public var \(pluralName): [\(v.swiftType)]")
        }
        
        lines.append("")
        
        // Initializer
        var initParams = ["object: String = \"list\"", "hasMore: Bool? = nil", "url: String? = nil"]
        for v in variantInfos {
            initParams.append("\(pluralPropertyName(v.caseName)): [\(v.swiftType)] = []")
        }
        lines.append("    public init(\(initParams.joined(separator: ", "))) {")
        lines.append("        self.object = object")
        lines.append("        self.hasMore = hasMore")
        lines.append("        self.url = url")
        for v in variantInfos {
            let name = pluralPropertyName(v.caseName)
            lines.append("        self.\(name) = \(name)")
        }
        lines.append("    }")
        
        lines.append("")
        lines.append("    // MARK: - Polymorphic Decoding")
        lines.append("")
        lines.append("    private struct ObjectDiscriminator: Codable {")
        lines.append("        let object: String")
        lines.append("    }")
        lines.append("")
        lines.append("    private enum CodingKeys: String, CodingKey {")
        lines.append("        case object")
        lines.append("        case hasMore = \"has_more\"")
        lines.append("        case url")
        lines.append("        case data")
        lines.append("    }")
        lines.append("")
        
        // Custom init(from:)
        lines.append("    public init(from decoder: Decoder) throws {")
        lines.append("        let container = try decoder.container(keyedBy: CodingKeys.self)")
        lines.append("        self.object = try container.decode(String.self, forKey: .object)")
        lines.append("        self.hasMore = try container.decodeIfPresent(Bool.self, forKey: .hasMore)")
        lines.append("        self.url = try container.decodeIfPresent(String.self, forKey: .url)")
        lines.append("")
        
        // Initialize typed arrays
        for v in variantInfos {
            lines.append("        var \(pluralPropertyName(v.caseName)): [\(v.swiftType)] = []")
        }
        lines.append("")
        
        lines.append("        if var dataContainer = try? container.nestedUnkeyedContainer(forKey: .data) {")
        lines.append("            var itemsContainer = try container.nestedUnkeyedContainer(forKey: .data)")
        lines.append("            while !dataContainer.isAtEnd {")
        lines.append("                let discriminator = try dataContainer.decode(ObjectDiscriminator.self)")
        lines.append("                switch discriminator.object {")
        for v in variantInfos {
            lines.append("                case \"\(v.id)\":")
            lines.append("                    \(pluralPropertyName(v.caseName)).append(try itemsContainer.decode(\(v.swiftType).self))")
        }
        lines.append("                default:")
        lines.append("                    _ = try itemsContainer.decode(ObjectDiscriminator.self)")
        lines.append("                }")
        lines.append("            }")
        lines.append("        }")
        lines.append("")
        
        for v in variantInfos {
            lines.append("        self.\(pluralPropertyName(v.caseName)) = \(pluralPropertyName(v.caseName))")
        }
        
        lines.append("    }")
        lines.append("")
        
        lines.append(contentsOf: [
            "    public func encode(to encoder: Encoder) throws {",
            "        var container = encoder.container(keyedBy: CodingKeys.self)",
            "        try container.encode(object, forKey: .object)",
            "        try container.encodeIfPresent(hasMore, forKey: .hasMore)",
            "        try container.encodeIfPresent(url, forKey: .url)",
            "    }",
            "",
        ])
        
        lines.append("}")
        
        return lines
    }
    
    /// Pluralize a camelCase enum case name for use as a typed array property
    private func pluralPropertyName(_ caseName: String) -> String {
        // bankAccount → bankAccounts, card → cards
        if caseName.hasSuffix("s") || caseName.hasSuffix("x") || caseName.hasSuffix("z") {
            return caseName + "es"
        }
        return caseName + "s"
    }
    
    private func generateListType(resource: StripeResource) -> [String] {
        return [
            "public struct \(resource.swiftTypeName)List: Codable, Sendable {",
            "    public var object: String",
            "    public var hasMore: Bool?",
            "    public var url: String?",
            "    public var data: [\(resource.swiftTypeName)]?",
            "",
            "    public enum CodingKeys: String, CodingKey {",
            "        case object",
            "        case hasMore = \"has_more\"",
            "        case url",
            "        case data",
            "    }",
            "}",
        ]
    }
    
    // MARK: - Helpers
    
    private func schemaIdToSwiftType(_ resourceId: String) -> String {
        let baseName: String
        if resourceId.contains(".") {
            baseName = String(resourceId.split(separator: ".").last ?? Substring(resourceId))
        } else {
            baseName = resourceId
        }
        return baseName
            .split(separator: "_")
            .map { $0.capitalized }
            .joined()
    }
}
