// MARK: - Param Generator
// Generates typed Swift parameter structs from OpenAPI requestBody schemas.
// Each POST operation gets a {Resource}{Action}Params struct with all fields typed.
// Nested objects become sub-structs up to 4 levels deep, then fall back to [String: String]?.
//
// Every params struct includes an optional `expand: [String]?` field.

import Foundation

struct ParamGenerator {
    let spec: OpenAPISpec
    let parser: SpecParser
    /// Deterministic mapping of schema name → API paths, built by SpecParser.buildPathMapping()
    let pathMapping: [String: [(method: String, path: String)]]
    
    /// Maximum nesting depth for typed sub-structs
    private let maxDepth = 20
    
    // MARK: - Per-Resource Generation
    
    /// Generate param structs for a resource as an extension file.
    /// Returns nil if the resource has no POST operations with requestBody.
    func generate(resource: StripeResource) -> String? {
        let operations = findOperations(for: resource)
        guard !operations.isEmpty else { return nil }
        
        var lines: [String] = []
        
        // File header
        lines.append("//")
        lines.append("//  \(resource.swiftTypeName)+Params.swift")
        lines.append("//  StripeKit")
        lines.append("//")
        lines.append("//  Generated by stripe-kit-codegen")
        lines.append("//")
        lines.append("")
        lines.append("import Foundation")
        lines.append("")
        
        // Collect all sub-structs generated during param generation
        var allSubStructs: [(name: String, lines: [String])] = []
        
        for (action, schema, requiredFields) in operations {
            let stem = "\(resource.swiftTypeName)\(action)"
            let (structLines, subStructs) = generateParamStruct(
                stem: stem,
                schema: schema,
                requiredFields: requiredFields,
                depth: 0
            )
            lines.append(contentsOf: structLines)
            lines.append("")
            allSubStructs.append(contentsOf: subStructs)
        }
        
        // Emit all sub-structs
        for (_, subLines) in allSubStructs {
            lines.append(contentsOf: subLines)
            lines.append("")
        }
        
        return lines.joined(separator: "\n")
    }
    
    // MARK: - Struct Generation
    
    /// Generate a single param struct from an inline schema.
    /// `stem` is the name without "Params" suffix, e.g. "AccountCreate".
    /// Top-level structs get "Params" suffix: "AccountCreateParams".
    /// Sub-structs use plain stem: "AccountCreateBusinessProfile".
    private func generateParamStruct(
        stem: String,
        schema: PropertyObject,
        requiredFields: Set<String>,
        depth: Int
    ) -> (lines: [String], subStructs: [(name: String, lines: [String])]) {
        let structName = depth == 0 ? "\(stem)Params" : stem
        var lines: [String] = []
        var subStructs: [(name: String, lines: [String])] = []
        
        let properties = schema.properties ?? [:]
        let sorted = properties.sorted { $0.key < $1.key }
        
        // Doc comment from schema description
        if let desc = schema.description, !desc.isEmpty {
            let cleaned = cleanDescription(desc)
            let wrapped = wordWrap(cleaned, lineLength: 100)
            for line in wrapped {
                lines.append("/// \(line)")
            }
        }
        
        lines.append("public struct \(structName): StripeParams {")
        
        // Required fields first, then optional, sorted alphabetically within each group
        let requiredProps = sorted.filter { requiredFields.contains($0.key) }
        let optionalProps = sorted.filter { !requiredFields.contains($0.key) }
        
        for (propName, prop) in requiredProps {
            lines.append(contentsOf: generateParamProperty(
                name: propName,
                prop: prop,
                isRequired: true,
                parentStem: stem,
                depth: depth,
                subStructs: &subStructs
            ))
        }
        
        for (propName, prop) in optionalProps {
            lines.append(contentsOf: generateParamProperty(
                name: propName,
                prop: prop,
                isRequired: false,
                parentStem: stem,
                depth: depth,
                subStructs: &subStructs
            ))
        }
        
        // Only top-level params have expand (sub-types don't make separate API calls)
        if depth == 0 && !properties.keys.contains("expand") {
            lines.append("    /// Specifies which fields to expand in the response.")
            lines.append("    public var expand: [String]?")
        }
        
        // Memberwise initializer with only required params
        lines.append("")
        if !requiredProps.isEmpty {
            let initParams = requiredProps.map { (propName, prop) -> String in
                let swiftName = snakeToCamel(propName)
                // Use anyOf resolution when available, matching property type
                let swiftType: String
                if let anyOf = prop.anyOf, !anyOf.isEmpty {
                    var dummySubStructs: [(name: String, lines: [String])] = []
                    swiftType = resolveAnyOfParam(anyOf, parentStem: stem, propName: propName, depth: depth, subStructs: &dummySubStructs)
                } else {
                    swiftType = paramTypeString(prop, parentStem: stem, propName: propName, depth: depth)
                }
                return "\(escapedSwiftName(swiftName)): \(swiftType)"
            }.joined(separator: ", ")
            
            // Add optional params with defaults
            let optionalInitParams = optionalProps.map { (propName, prop) -> String in
                let swiftName = snakeToCamel(propName)
                let swiftType: String
                if let anyOf = prop.anyOf, !anyOf.isEmpty {
                    var dummySubStructs: [(name: String, lines: [String])] = []
                    swiftType = resolveAnyOfParam(anyOf, parentStem: stem, propName: propName, depth: depth, subStructs: &dummySubStructs)
                } else {
                    swiftType = paramTypeString(prop, parentStem: stem, propName: propName, depth: depth)
                }
                return "\(escapedSwiftName(swiftName)): \(swiftType)? = nil"
            }.joined(separator: ", ")
            
            let allParams = optionalInitParams.isEmpty ? initParams : "\(initParams), \(optionalInitParams)"
            
            lines.append("    public init(\(allParams)) {")
            for (propName, _) in requiredProps {
                let swiftName = snakeToCamel(propName)
                lines.append("        self.\(escapedSwiftName(swiftName)) = \(escapedSwiftName(swiftName))")
            }
            for (propName, _) in optionalProps {
                let swiftName = snakeToCamel(propName)
                lines.append("        self.\(escapedSwiftName(swiftName)) = \(escapedSwiftName(swiftName))")
            }
            lines.append("    }")
        } else if !optionalProps.isEmpty {
            // All-optional: memberwise init with nil defaults
            let initParams = optionalProps.map { (propName, prop) -> String in
                let swiftName = snakeToCamel(propName)
                let swiftType: String
                if let anyOf = prop.anyOf, !anyOf.isEmpty {
                    var dummySubStructs: [(name: String, lines: [String])] = []
                    swiftType = resolveAnyOfParam(anyOf, parentStem: stem, propName: propName, depth: depth, subStructs: &dummySubStructs)
                } else {
                    swiftType = paramTypeString(prop, parentStem: stem, propName: propName, depth: depth)
                }
                return "\(escapedSwiftName(swiftName)): \(swiftType)? = nil"
            }.joined(separator: ", ")
            
            lines.append("    public init(\(initParams)) {")
            for (propName, _) in optionalProps {
                let swiftName = snakeToCamel(propName)
                lines.append("        self.\(escapedSwiftName(swiftName)) = \(escapedSwiftName(swiftName))")
            }
            lines.append("    }")
        } else {
            lines.append("    public init() {}")
        }
        
        // CodingKeys
        let needsCodingKeys = sorted.contains { snakeToCamel($0.key) != $0.key }
        if needsCodingKeys {
            lines.append("")
            lines.append("    public enum CodingKeys: String, CodingKey {")
            for (propName, _) in sorted {
                let swiftName = snakeToCamel(propName)
                if swiftName == propName {
                    lines.append("        case \(escapedSwiftName(swiftName))")
                } else {
                    lines.append("        case \(escapedSwiftName(swiftName)) = \"\(propName)\"")
                }
            }
            if depth == 0 && !properties.keys.contains("expand") {
                lines.append("        case expand")
            }
            lines.append("    }")
        }
        
        lines.append("}")
        
        return (lines, subStructs)
    }
    
    // MARK: - Property Generation
    
    private func generateParamProperty(
        name: String,
        prop: PropertyObject,
        isRequired: Bool,
        parentStem: String,
        depth: Int,
        subStructs: inout [(name: String, lines: [String])]
    ) -> [String] {
        var lines: [String] = []
        let swiftName = snakeToCamel(name)
        
        // Doc comment
        if let desc = prop.description, !desc.isEmpty {
            let cleaned = cleanDescription(desc)
            let wrapped = wordWrap(cleaned, lineLength: 100)
            for line in wrapped {
                lines.append("    /// \(line)")
            }
        }
        
        let swiftType = paramTypeString(prop, parentStem: parentStem, propName: name, depth: depth)
        let optionalMark = isRequired ? "" : "?"
        
        // If this is a nested object type, generate a sub-struct
        if let props = prop.properties, !props.isEmpty, depth < maxDepth {
            let childStem = "\(parentStem)\(capitalize(snakeToCamel(name)))"
            let subRequired = Set(prop.required ?? [])
            let (subLines, nestedSubs) = generateParamStruct(
                stem: childStem,
                schema: prop,
                requiredFields: subRequired,
                depth: depth + 1
            )
            subStructs.append((childStem, subLines))
            subStructs.append(contentsOf: nestedSubs)
        }
        
        // If this is an array of objects, generate a sub-struct for the items
        if prop.type == "array",
           let items = prop.items,
           let itemProps = items.properties, !itemProps.isEmpty,
           depth < maxDepth {
            let childStem = "\(parentStem)\(capitalize(snakeToCamel(name)))"
            let subRequired = Set(items.required ?? [])
            let (subLines, nestedSubs) = generateParamStruct(
                stem: childStem,
                schema: items,
                requiredFields: subRequired,
                depth: depth + 1
            )
            subStructs.append((childStem, subLines))
            subStructs.append(contentsOf: nestedSubs)
        }
        
        // Handle anyOf — resolve to the most specific non-string variant
        if let anyOf = prop.anyOf, !anyOf.isEmpty {
            let resolved = resolveAnyOfParam(anyOf, parentStem: parentStem, propName: name, depth: depth, subStructs: &subStructs)
            lines.append("    public var \(escapedSwiftName(swiftName)): \(resolved)\(optionalMark)")
            return lines
        }
        
        lines.append("    public var \(escapedSwiftName(swiftName)): \(swiftType)\(optionalMark)")
        return lines
    }
    
    // MARK: - Type Resolution
    
    private func paramTypeString(
        _ prop: PropertyObject,
        parentStem: String,
        propName: String,
        depth: Int
    ) -> String {
        // Handle $ref
        if let ref = prop.ref {
            let typeName = refToTypeName(ref)
            return parser.schemaNameToSwiftType(typeName)
        }
        
        // Handle enum
        if let enumCases = prop.enum, !enumCases.isEmpty {
            return "\(parentStem)\(capitalize(snakeToCamel(propName)))"
        }
        
        switch prop.type {
        case "string":
            return "String"
        case "integer":
            return "Int"
        case "number":
            return "Double"
        case "boolean":
            return "Bool"
        case "array":
            if let items = prop.items {
                let elementType = paramTypeString(items, parentStem: parentStem, propName: propName, depth: depth)
                return "[\(elementType)]"
            }
            return "[String]"
        case "object":
            if let _ = prop.additionalProperties {
                return "[String: String]"
            }
            if let props = prop.properties, !props.isEmpty {
                if depth < maxDepth {
                    return "\(parentStem)\(capitalize(snakeToCamel(propName)))"
                } else {
                    return "[String: String]"
                }
            }
            return "[String: String]"
        default:
            return "String"
        }
    }
    
    private func resolveAnyOfParam(
        _ variants: [PropertyObject],
        parentStem: String,
        propName: String,
        depth: Int,
        subStructs: inout [(name: String, lines: [String])]
    ) -> String {
        // Filter out empty-string enum variants (Stripe uses "" to mean "unset")
        let nonEmpty = variants.filter { variant in
            if let enumVals = variant.enum, enumVals == [""] { return false }
            return true
        }
        
        // If only one non-empty variant, use it
        if nonEmpty.count == 1, let single = nonEmpty.first {
            // If it's an object with properties, generate sub-struct
            if let props = single.properties, !props.isEmpty, depth < maxDepth {
                let childStem = "\(parentStem)\(capitalize(snakeToCamel(propName)))"
                let subRequired = Set(single.required ?? [])
                let (subLines, nestedSubs) = generateParamStruct(
                    stem: childStem,
                    schema: single,
                    requiredFields: subRequired,
                    depth: depth + 1
                )
                let structName = childStem
                subStructs.append((structName, subLines))
                subStructs.append(contentsOf: nestedSubs)
                return structName
            }
            // If it's an array of objects, generate sub-struct for the items
            if single.type == "array",
               let items = single.items,
               let itemProps = items.properties, !itemProps.isEmpty,
               depth < maxDepth {
                let childStem = "\(parentStem)\(capitalize(snakeToCamel(propName)))"
                let subRequired = Set(items.required ?? [])
                let (subLines, nestedSubs) = generateParamStruct(
                    stem: childStem,
                    schema: items,
                    requiredFields: subRequired,
                    depth: depth + 1
                )
                let structName = childStem
                subStructs.append((structName, subLines))
                subStructs.append(contentsOf: nestedSubs)
                return "[\(structName)]"
            }
            return paramTypeString(single, parentStem: parentStem, propName: propName, depth: depth)
        }
        
        // Multiple variants — fall back to String
        return "String"
    }
    
    // MARK: - Enum Generation for Params
    
    /// Generate enums that appear in param properties (e.g., capture_method: automatic|manual)
    func generateParamEnums(resource: StripeResource) -> [String] {
        let operations = findOperations(for: resource)
        var lines: [String] = []
        var seenEnumNames = Set<String>()
        
        for (action, schema, _) in operations {
            let stem = "\(resource.swiftTypeName)\(action)"
            let props = schema.properties ?? [:]
            
            for (propName, prop) in props.sorted(by: { $0.key < $1.key }) {
                if let enumCases = prop.enum, !enumCases.isEmpty {
                    let enumName = "\(stem)\(capitalize(snakeToCamel(propName)))"
                    guard !seenEnumNames.contains(enumName) else { continue }
                    seenEnumNames.insert(enumName)
                    lines.append(contentsOf: generateEnum(name: enumName, cases: enumCases))
                    lines.append("")
                }
                // Also check anyOf for nested enum cases
                collectNestedEnums(
                    prop: prop,
                    parentName: stem,
                    propName: propName,
                    lines: &lines,
                    depth: 0,
                    seenEnumNames: &seenEnumNames
                )
            }
        }
        
        return lines
    }
    
    private func collectNestedEnums(
        prop: PropertyObject,
        parentName: String,
        propName: String,
        lines: inout [String],
        depth: Int,
        seenEnumNames: inout Set<String>
    ) {
        guard depth < maxDepth else { return }
        
        if let props = prop.properties {
            for (subName, subProp) in props.sorted(by: { $0.key < $1.key }) {
                let subParent = "\(parentName)\(capitalize(snakeToCamel(propName)))"
                if let enumCases = subProp.enum, !enumCases.isEmpty {
                    let enumName = "\(subParent)\(capitalize(snakeToCamel(subName)))"
                    if !seenEnumNames.contains(enumName) {
                        seenEnumNames.insert(enumName)
                        lines.append(contentsOf: generateEnum(name: enumName, cases: enumCases))
                        lines.append("")
                    }
                }
                collectNestedEnums(
                    prop: subProp,
                    parentName: subParent,
                    propName: subName,
                    lines: &lines,
                    depth: depth + 1,
                    seenEnumNames: &seenEnumNames
                )
            }
        }
        
        // Recurse into array items
        if prop.type == "array", let items = prop.items {
            // If the array items have an enum directly
            if let enumCases = items.enum, !enumCases.isEmpty {
                let enumName = "\(parentName)\(capitalize(snakeToCamel(propName)))"
                if !seenEnumNames.contains(enumName) {
                    seenEnumNames.insert(enumName)
                    lines.append(contentsOf: generateEnum(name: enumName, cases: enumCases))
                    lines.append("")
                }
            }
            // If the array items are objects with properties, recurse into them
            if let itemProps = items.properties {
                for (subName, subProp) in itemProps.sorted(by: { $0.key < $1.key }) {
                    let subParent = "\(parentName)\(capitalize(snakeToCamel(propName)))"
                    if let enumCases = subProp.enum, !enumCases.isEmpty {
                        let enumName = "\(subParent)\(capitalize(snakeToCamel(subName)))"
                        if !seenEnumNames.contains(enumName) {
                            seenEnumNames.insert(enumName)
                            lines.append(contentsOf: generateEnum(name: enumName, cases: enumCases))
                            lines.append("")
                        }
                    }
                    collectNestedEnums(
                        prop: subProp,
                        parentName: subParent,
                        propName: subName,
                        lines: &lines,
                        depth: depth + 1,
                        seenEnumNames: &seenEnumNames
                    )
                }
            }
        }
        
        // Recurse into anyOf variants
        if let anyOf = prop.anyOf {
            for variant in anyOf {
                collectNestedEnums(
                    prop: variant,
                    parentName: parentName,
                    propName: propName,
                    lines: &lines,
                    depth: depth,
                    seenEnumNames: &seenEnumNames
                )
            }
        }
    }
    
    private func generateEnum(name: String, cases: [String]) -> [String] {
        // Filter out empty string ("" means unset)
        let filtered = cases.filter { !$0.isEmpty }
        guard !filtered.isEmpty else { return [] }
        
        var lines: [String] = []
        var seenCases = Set<String>()
        lines.append("public enum \(name): String, Codable, Sendable {")
        for rawCase in filtered {
            let swiftCase = enumCaseToSwift(rawCase)
            guard !seenCases.contains(swiftCase) else { continue }
            seenCases.insert(swiftCase)
            if swiftCase != rawCase {
                lines.append("    case \(swiftCase) = \"\(rawCase)\"")
            } else {
                lines.append("    case \(swiftCase)")
            }
        }
        lines.append("}")
        return lines
    }
    
    // MARK: - Operation Discovery
    
    /// Find all POST operations for a resource, returning (action, bodySchema, requiredFields)
    func findOperations(for resource: StripeResource) -> [(action: String, schema: PropertyObject, required: Set<String>)] {
        var results: [(action: String, path: String, schema: PropertyObject, required: Set<String>)] = []
        
        // Deterministic: look up paths directly from the spec-derived mapping
        guard let resourcePaths = pathMapping[resource.schemaName] else { return [] }
        // Get unique paths
        let uniquePaths = Set(resourcePaths.map { $0.path })
        
        // Derive basePath: shortest path that is a segment-aligned prefix of at least
        // one other path.  Deterministic — no scoring, no tie-breaking ambiguity.
        let basePath: String = {
            let sorted = uniquePaths.sorted { $0.count < $1.count }
            for candidate in sorted {
                let isPrefix = sorted.contains { other in
                    other != candidate && other.hasPrefix(candidate + "/")
                }
                if isPrefix { return candidate }
            }
            return sorted.first ?? ""
        }()
        
        for path in uniquePaths.sorted() {
            guard let pathItem = spec.paths[path] else { continue }
            
            // Only POST operations have requestBody we care about
            guard let post = pathItem.post,
                  let rb = post.requestBody,
                  let content = rb.content?["application/x-www-form-urlencoded"],
                  let schema = content.schema,
                  let _ = schema.properties, !schema.properties!.isEmpty
            else { continue }
            
            let action = deriveAction(path: path, pathPrefix: basePath, operationId: post.operationId)
            let required = Set(schema.required ?? [])
            
            results.append((action, path, schema, required))
        }
        
        // Deduplicate by action — prefer operations whose path starts with basePath
        // (the resource's own namespace) over cross-resource aliases.
        var bestByAction: [String: (action: String, path: String, schema: PropertyObject, required: Set<String>)] = [:]
        for op in results {
            if let existing = bestByAction[op.action] {
                let existingIsLocal = existing.path.hasPrefix(basePath)
                let newIsLocal = op.path.hasPrefix(basePath)
                if !existingIsLocal && newIsLocal {
                    bestByAction[op.action] = op
                }
            } else {
                bestByAction[op.action] = op
            }
        }
        
        return bestByAction.values
            .sorted { $0.action < $1.action }
            .map { ($0.action, $0.schema, $0.required) }
    }
    
    /// Derive a friendly action name from the path
    /// /v1/payment_intents → "Create"
    /// /v1/payment_intents/{intent} → "Update"
    /// /v1/payment_intents/{intent}/cancel → "Cancel"
    /// /v1/payment_intents/{intent}/capture → "Capture"
    private func deriveAction(path: String, pathPrefix: String, operationId: String?) -> String {
        let basePrefixParamCount = pathPrefix.split(separator: "/").filter { $0.hasPrefix("{") }.count
        let totalPathParams = path.split(separator: "/").filter { $0.hasPrefix("{") }.count
        
        // POST basePath (no path params beyond prefix) → Create
        if totalPathParams == basePrefixParamCount && path == pathPrefix {
            return "Create"
        }
        
        // POST basePath/{id} (one extra path param, no trailing action) → Update
        let trailingParts = path.hasPrefix(pathPrefix) ? String(path.dropFirst(pathPrefix.count)) : ""
        let trailingNonParams = trailingParts.split(separator: "/").filter { !$0.hasPrefix("{") }
        
        if trailingNonParams.isEmpty && totalPathParams == basePrefixParamCount + 1 {
            return "Update"
        }
        
        // POST with trailing action segment → named action
        if let actionSlug = trailingNonParams.last {
            return capitalize(snakeToCamel(String(actionSlug)))
        }
        
        return "Create"
    }
    
    // MARK: - Helpers
    
    private func refToTypeName(_ ref: String) -> String {
        ref.split(separator: "/").last.map(String.init) ?? ref
    }
}
