// MARK: - Param Generator
// Generates typed Swift parameter structs from OpenAPI requestBody schemas.
// Each POST operation gets a {Resource}{Action}Params struct with all fields typed.
// Nested objects become sub-structs up to 4 levels deep, then fall back to [String: String]?.
//
// Every params struct includes an optional `expand: [String]?` field.

import Foundation

struct ParamGenerator {
    let spec: OpenAPISpec
    let parser: SpecParser
    /// Deterministic mapping of schema name → API paths, built by SpecParser.buildPathMapping()
    let pathMapping: [String: [(method: String, path: String)]]
    
    /// Maximum nesting depth for typed sub-structs
    private let maxDepth = 20
    
    // MARK: - Per-Resource Generation
    
    /// Generate param structs for a resource as an extension file.
    /// Returns nil if the resource has no POST operations with requestBody.
    func generate(resource: StripeResource) -> String? {
        let operations = findOperations(for: resource)
        guard !operations.isEmpty else { return nil }
        
        var lines: [String] = []
        
        // File header
        lines.append("//")
        lines.append("//  \(resource.swiftTypeName)+Params.swift")
        lines.append("//  StripeKit")
        lines.append("//")
        lines.append("//  Generated by stripe-kit-codegen")
        lines.append("//")
        lines.append("")
        lines.append("import Foundation")
        lines.append("")
        
        // Collect all sub-structs generated during param generation
        var allSubStructs: [(name: String, lines: [String])] = []
        
        for (action, schema, requiredFields) in operations {
            let structName = "\(resource.swiftTypeName)\(action)Params"
            let (structLines, subStructs) = generateParamStruct(
                name: structName,
                schema: schema,
                requiredFields: requiredFields,
                depth: 0
            )
            lines.append(contentsOf: structLines)
            lines.append("")
            allSubStructs.append(contentsOf: subStructs)
        }
        
        // Emit all sub-structs
        for (_, subLines) in allSubStructs {
            lines.append(contentsOf: subLines)
            lines.append("")
        }
        
        return lines.joined(separator: "\n")
    }
    
    // MARK: - Struct Generation
    
    /// Generate a single param struct from an inline schema.
    /// Returns the struct lines and any sub-structs that need to be emitted.
    private func generateParamStruct(
        name: String,
        schema: PropertyObject,
        requiredFields: Set<String>,
        depth: Int
    ) -> (lines: [String], subStructs: [(name: String, lines: [String])]) {
        var lines: [String] = []
        var subStructs: [(name: String, lines: [String])] = []
        
        let properties = schema.properties ?? [:]
        let sorted = properties.sorted { $0.key < $1.key }
        
        // Doc comment from schema description
        if let desc = schema.description, !desc.isEmpty {
            let cleaned = cleanDescription(desc)
            let wrapped = wordWrap(cleaned, lineLength: 100)
            for line in wrapped {
                lines.append("/// \(line)")
            }
        }
        
        lines.append("public struct \(name): StripeParams {")
        
        // Required fields first, then optional, sorted alphabetically within each group
        let requiredProps = sorted.filter { requiredFields.contains($0.key) }
        let optionalProps = sorted.filter { !requiredFields.contains($0.key) }
        
        for (propName, prop) in requiredProps {
            lines.append(contentsOf: generateParamProperty(
                name: propName,
                prop: prop,
                isRequired: true,
                parentStructName: name,
                depth: depth,
                subStructs: &subStructs
            ))
        }
        
        for (propName, prop) in optionalProps {
            lines.append(contentsOf: generateParamProperty(
                name: propName,
                prop: prop,
                isRequired: false,
                parentStructName: name,
                depth: depth,
                subStructs: &subStructs
            ))
        }
        
        // Always include expand
        if !properties.keys.contains("expand") {
            lines.append("    /// Specifies which fields to expand in the response.")
            lines.append("    public var expand: [String]?")
        }
        
        // Memberwise initializer with only required params
        lines.append("")
        if !requiredProps.isEmpty {
            let initParams = requiredProps.map { (propName, prop) -> String in
                let swiftName = snakeToCamel(propName)
                // Use anyOf resolution when available, matching property type
                let swiftType: String
                if let anyOf = prop.anyOf, !anyOf.isEmpty {
                    var dummySubStructs: [(name: String, lines: [String])] = []
                    swiftType = resolveAnyOfParam(anyOf, parentStructName: name, propName: propName, depth: depth, subStructs: &dummySubStructs)
                } else {
                    swiftType = paramTypeString(prop, parentStructName: name, propName: propName, depth: depth)
                }
                return "\(swiftName): \(swiftType)"
            }.joined(separator: ", ")
            
            lines.append("    public init(\(initParams)) {")
            for (propName, _) in requiredProps {
                let swiftName = snakeToCamel(propName)
                lines.append("        self.\(swiftName) = \(swiftName)")
            }
            lines.append("    }")
        } else {
            // All-optional struct: emit default init so consumers don't have to
            // spell out every nil parameter (CodingKeys suppresses Swift's
            // synthesized memberwise init).
            lines.append("    public init() {}")
        }
        
        // CodingKeys
        let needsCodingKeys = sorted.contains { snakeToCamel($0.key) != $0.key }
        if needsCodingKeys {
            lines.append("")
            lines.append("    public enum CodingKeys: String, CodingKey {")
            for (propName, _) in sorted {
                let swiftName = snakeToCamel(propName)
                if swiftName != propName {
                    lines.append("        case \(escapedSwiftName(swiftName)) = \"\(propName)\"")
                } else {
                    lines.append("        case \(escapedSwiftName(swiftName))")
                }
            }
            if !properties.keys.contains("expand") {
                lines.append("        case expand")
            }
            lines.append("    }")
        }
        
        lines.append("}")
        
        return (lines, subStructs)
    }
    
    // MARK: - Property Generation
    
    private func generateParamProperty(
        name: String,
        prop: PropertyObject,
        isRequired: Bool,
        parentStructName: String,
        depth: Int,
        subStructs: inout [(name: String, lines: [String])]
    ) -> [String] {
        var lines: [String] = []
        let swiftName = snakeToCamel(name)
        
        // Doc comment
        if let desc = prop.description, !desc.isEmpty {
            let cleaned = cleanDescription(desc)
            let wrapped = wordWrap(cleaned, lineLength: 100)
            for line in wrapped {
                lines.append("    /// \(line)")
            }
        }
        
        let swiftType = paramTypeString(prop, parentStructName: parentStructName, propName: name, depth: depth)
        let optionalMark = isRequired ? "" : "?"
        
        // If this is a nested object type, generate a sub-struct
        if let props = prop.properties, !props.isEmpty, depth < maxDepth {
            let subStructName = "\(parentStructName)\(capitalize(snakeToCamel(name)))"
            let subRequired = Set(prop.required ?? [])
            let (subLines, nestedSubs) = generateParamStruct(
                name: subStructName,
                schema: prop,
                requiredFields: subRequired,
                depth: depth + 1
            )
            subStructs.append((subStructName, subLines))
            subStructs.append(contentsOf: nestedSubs)
        }
        
        // If this is an array of objects, generate a sub-struct for the items
        if prop.type == "array",
           let items = prop.items,
           let itemProps = items.properties, !itemProps.isEmpty,
           depth < maxDepth {
            let subStructName = "\(parentStructName)\(capitalize(snakeToCamel(name)))"
            let subRequired = Set(items.required ?? [])
            let (subLines, nestedSubs) = generateParamStruct(
                name: subStructName,
                schema: items,
                requiredFields: subRequired,
                depth: depth + 1
            )
            subStructs.append((subStructName, subLines))
            subStructs.append(contentsOf: nestedSubs)
        }
        
        // Handle anyOf — resolve to the most specific non-string variant
        if let anyOf = prop.anyOf, !anyOf.isEmpty {
            let resolved = resolveAnyOfParam(anyOf, parentStructName: parentStructName, propName: name, depth: depth, subStructs: &subStructs)
            lines.append("    public var \(escapedSwiftName(swiftName)): \(resolved)\(optionalMark)")
            return lines
        }
        
        lines.append("    public var \(escapedSwiftName(swiftName)): \(swiftType)\(optionalMark)")
        return lines
    }
    
    // MARK: - Type Resolution
    
    private func paramTypeString(
        _ prop: PropertyObject,
        parentStructName: String,
        propName: String,
        depth: Int
    ) -> String {
        // Handle $ref
        if let ref = prop.ref {
            let typeName = refToTypeName(ref)
            return parser.schemaNameToSwiftType(typeName)
        }
        
        // Handle enum
        if let enumCases = prop.enum, !enumCases.isEmpty {
            // Generate inline enum name based on parent + property
            return "\(parentStructName)\(capitalize(snakeToCamel(propName)))"
        }
        
        switch prop.type {
        case "string":
            return "String"
        case "integer":
            return "Int"
        case "number":
            return "Double"
        case "boolean":
            return "Bool"
        case "array":
            if let items = prop.items {
                let elementType = paramTypeString(items, parentStructName: parentStructName, propName: propName, depth: depth)
                return "[\(elementType)]"
            }
            return "[String]"
        case "object":
            if let _ = prop.additionalProperties {
                return "[String: String]"
            }
            if let props = prop.properties, !props.isEmpty {
                if depth < maxDepth {
                    return "\(parentStructName)\(capitalize(snakeToCamel(propName)))"
                } else {
                    return "[String: String]"
                }
            }
            return "[String: String]"
        default:
            return "String"
        }
    }
    
    private func resolveAnyOfParam(
        _ variants: [PropertyObject],
        parentStructName: String,
        propName: String,
        depth: Int,
        subStructs: inout [(name: String, lines: [String])]
    ) -> String {
        // Filter out empty-string enum variants (Stripe uses "" to mean "unset")
        let nonEmpty = variants.filter { variant in
            if let enumVals = variant.enum, enumVals == [""] { return false }
            return true
        }
        
        // If only one non-empty variant, use it
        if nonEmpty.count == 1, let single = nonEmpty.first {
            // If it's an object with properties, generate sub-struct
            if let props = single.properties, !props.isEmpty, depth < maxDepth {
                let subStructName = "\(parentStructName)\(capitalize(snakeToCamel(propName)))"
                let subRequired = Set(single.required ?? [])
                let (subLines, nestedSubs) = generateParamStruct(
                    name: subStructName,
                    schema: single,
                    requiredFields: subRequired,
                    depth: depth + 1
                )
                subStructs.append((subStructName, subLines))
                subStructs.append(contentsOf: nestedSubs)
                return subStructName
            }
            // If it's an array of objects, generate sub-struct for the items
            if single.type == "array",
               let items = single.items,
               let itemProps = items.properties, !itemProps.isEmpty,
               depth < maxDepth {
                let subStructName = "\(parentStructName)\(capitalize(snakeToCamel(propName)))"
                let subRequired = Set(items.required ?? [])
                let (subLines, nestedSubs) = generateParamStruct(
                    name: subStructName,
                    schema: items,
                    requiredFields: subRequired,
                    depth: depth + 1
                )
                subStructs.append((subStructName, subLines))
                subStructs.append(contentsOf: nestedSubs)
                return "[\(subStructName)]"
            }
            return paramTypeString(single, parentStructName: parentStructName, propName: propName, depth: depth)
        }
        
        // Multiple variants — fall back to String
        return "String"
    }
    
    // MARK: - Enum Generation for Params
    
    /// Generate enums that appear in param properties (e.g., capture_method: automatic|manual)
    func generateParamEnums(resource: StripeResource) -> [String] {
        let operations = findOperations(for: resource)
        var lines: [String] = []
        var seenEnumNames = Set<String>()
        
        for (action, schema, _) in operations {
            let structName = "\(resource.swiftTypeName)\(action)Params"
            let props = schema.properties ?? [:]
            
            for (propName, prop) in props.sorted(by: { $0.key < $1.key }) {
                if let enumCases = prop.enum, !enumCases.isEmpty {
                    let enumName = "\(structName)\(capitalize(snakeToCamel(propName)))"
                    guard !seenEnumNames.contains(enumName) else { continue }
                    seenEnumNames.insert(enumName)
                    lines.append(contentsOf: generateEnum(name: enumName, cases: enumCases))
                    lines.append("")
                }
                // Also check anyOf for nested enum cases
                collectNestedEnums(
                    prop: prop,
                    parentName: structName,
                    propName: propName,
                    lines: &lines,
                    depth: 0,
                    seenEnumNames: &seenEnumNames
                )
            }
        }
        
        return lines
    }
    
    private func collectNestedEnums(
        prop: PropertyObject,
        parentName: String,
        propName: String,
        lines: inout [String],
        depth: Int,
        seenEnumNames: inout Set<String>
    ) {
        guard depth < maxDepth else { return }
        
        if let props = prop.properties {
            for (subName, subProp) in props.sorted(by: { $0.key < $1.key }) {
                let subParent = "\(parentName)\(capitalize(snakeToCamel(propName)))"
                if let enumCases = subProp.enum, !enumCases.isEmpty {
                    let enumName = "\(subParent)\(capitalize(snakeToCamel(subName)))"
                    if !seenEnumNames.contains(enumName) {
                        seenEnumNames.insert(enumName)
                        lines.append(contentsOf: generateEnum(name: enumName, cases: enumCases))
                        lines.append("")
                    }
                }
                collectNestedEnums(
                    prop: subProp,
                    parentName: subParent,
                    propName: subName,
                    lines: &lines,
                    depth: depth + 1,
                    seenEnumNames: &seenEnumNames
                )
            }
        }
        
        // Recurse into array items
        if prop.type == "array", let items = prop.items {
            // If the array items have an enum directly
            if let enumCases = items.enum, !enumCases.isEmpty {
                let enumName = "\(parentName)\(capitalize(snakeToCamel(propName)))"
                if !seenEnumNames.contains(enumName) {
                    seenEnumNames.insert(enumName)
                    lines.append(contentsOf: generateEnum(name: enumName, cases: enumCases))
                    lines.append("")
                }
            }
            // If the array items are objects with properties, recurse into them
            if let itemProps = items.properties {
                for (subName, subProp) in itemProps.sorted(by: { $0.key < $1.key }) {
                    let subParent = "\(parentName)\(capitalize(snakeToCamel(propName)))"
                    if let enumCases = subProp.enum, !enumCases.isEmpty {
                        let enumName = "\(subParent)\(capitalize(snakeToCamel(subName)))"
                        if !seenEnumNames.contains(enumName) {
                            seenEnumNames.insert(enumName)
                            lines.append(contentsOf: generateEnum(name: enumName, cases: enumCases))
                            lines.append("")
                        }
                    }
                    collectNestedEnums(
                        prop: subProp,
                        parentName: subParent,
                        propName: subName,
                        lines: &lines,
                        depth: depth + 1,
                        seenEnumNames: &seenEnumNames
                    )
                }
            }
        }
        
        // Recurse into anyOf variants
        if let anyOf = prop.anyOf {
            for variant in anyOf {
                collectNestedEnums(
                    prop: variant,
                    parentName: parentName,
                    propName: propName,
                    lines: &lines,
                    depth: depth,
                    seenEnumNames: &seenEnumNames
                )
            }
        }
    }
    
    private func generateEnum(name: String, cases: [String]) -> [String] {
        // Filter out empty string ("" means unset)
        let filtered = cases.filter { !$0.isEmpty }
        guard !filtered.isEmpty else { return [] }
        
        var lines: [String] = []
        var seenCases = Set<String>()
        lines.append("public enum \(name): String, Codable, Sendable {")
        for rawCase in filtered {
            let swiftCase = enumCaseToSwift(rawCase)
            guard !seenCases.contains(swiftCase) else { continue }
            seenCases.insert(swiftCase)
            if swiftCase != rawCase {
                lines.append("    case \(swiftCase) = \"\(rawCase)\"")
            } else {
                lines.append("    case \(swiftCase)")
            }
        }
        lines.append("}")
        return lines
    }
    
    // MARK: - Operation Discovery
    
    /// Find all POST operations for a resource, returning (action, bodySchema, requiredFields)
    func findOperations(for resource: StripeResource) -> [(action: String, schema: PropertyObject, required: Set<String>)] {
        var results: [(String, PropertyObject, Set<String>)] = []
        
        // Deterministic: look up paths directly from the spec-derived mapping
        guard let resourcePaths = pathMapping[resource.schemaName] else { return [] }
        
        // Get unique paths and derive basePath (shortest = collection endpoint)
        let uniquePaths = Set(resourcePaths.map { $0.path })
        let basePath = uniquePaths.min(by: { $0.count < $1.count }) ?? ""
        
        for path in uniquePaths {
            guard let pathItem = spec.paths[path] else { continue }
            
            // Only POST operations have requestBody we care about
            guard let post = pathItem.post,
                  let rb = post.requestBody,
                  let content = rb.content?["application/x-www-form-urlencoded"],
                  let schema = content.schema,
                  let _ = schema.properties, !schema.properties!.isEmpty
            else { continue }
            
            let action = deriveAction(path: path, pathPrefix: basePath, operationId: post.operationId)
            let required = Set(schema.required ?? [])
            
            results.append((action, schema, required))
        }
        
        // Deduplicate by action name (keep first)
        var seen = Set<String>()
        results = results.filter { op in
            if seen.contains(op.0) { return false }
            seen.insert(op.0)
            return true
        }
        
        return results.sorted { $0.0 < $1.0 }
    }
    
    /// Derive a friendly action name from the path
    /// /v1/payment_intents → "Create"
    /// /v1/payment_intents/{intent} → "Update"
    /// /v1/payment_intents/{intent}/cancel → "Cancel"
    /// /v1/payment_intents/{intent}/capture → "Capture"
    private func deriveAction(path: String, pathPrefix: String, operationId: String?) -> String {
        let rawSuffix = path.hasPrefix(pathPrefix) ? String(path.dropFirst(pathPrefix.count)) : nil
        // Ensure prefix match is segment-aligned: suffix must start with "/" or be empty
        let suffix: String
        if let rawSuffix, rawSuffix.isEmpty || rawSuffix.hasPrefix("/") {
            suffix = rawSuffix
        } else {
            suffix = ""
        }
        
        if suffix.isEmpty {
            return "Create"
        }
        
        // Remove leading slash and path params
        let parts = suffix
            .trimmingCharacters(in: CharacterSet(charactersIn: "/"))
            .split(separator: "/")
            .filter { !$0.hasPrefix("{") }
        
        if parts.isEmpty {
            // Only had path params: /v1/resource/{id} → Update
            return "Update"
        }
        
        // Use the last non-param segment as action name
        let actionSlug = String(parts.last!)
        return capitalize(snakeToCamel(actionSlug))
    }
    
    // MARK: - Helpers
    
    private func refToTypeName(_ ref: String) -> String {
        ref.split(separator: "/").last.map(String.init) ?? ref
    }
}
