// MARK: - Route Generator (Modern)
// Generates closure-based route structs from spec paths.
// Each resource gets a single struct with closure-stored operations.
// Includes .live(handler:) factory and .test stub.

import Foundation

struct RouteGenerator {
    let spec: OpenAPISpec
    let parser: SpecParser
    /// Deterministic mapping of schema name → API paths, built by SpecParser.buildPathMapping()
    let pathMapping: [String: [(method: String, path: String)]]
    
    /// Generate the closure-based route struct for a resource.
    /// Returns nil if the resource has no matching paths.
    func generate(resource: StripeResource) -> String? {
        let operations = findOperations(for: resource)
        guard !operations.isEmpty else { return nil }
        
        var lines: [String] = []
        
        // File header
        lines.append("//")
        lines.append("//  \(resource.swiftTypeName)Routes.swift")
        lines.append("//  StripeKit")
        lines.append("//")
        lines.append("//  Generated by stripe-kit-codegen")
        lines.append("//")
        lines.append("")
        lines.append("import Foundation")
        lines.append("import NIO")
        lines.append("import NIOHTTP1")
        lines.append("")
        
        // Route struct with closure properties
        lines.append("// MARK: - \(resource.swiftTypeName) Routes")
        lines.append("")
        lines.append("public struct \(resource.swiftTypeName)Routes: Sendable {")
        
        for op in operations {
            lines.append("")
            // Doc comment
            if let desc = op.description {
                let cleaned = cleanDescription(desc)
                let wrapped = wordWrap(cleaned, lineLength: 100)
                for line in wrapped {
                    lines.append("    /// \(line)")
                }
            }
            if op.isDeprecated {
                lines.append("    @available(*, deprecated, message: \"This API is deprecated by Stripe.\")")
            }
            lines.append("    public var \(escapedSwiftName(op.funcName)): \(closureType(for: op, resource: resource))")
        }
        
        lines.append("}")
        lines.append("")
        
        // .live(handler:) factory
        lines.append(contentsOf: generateLiveFactory(resource: resource, operations: operations))
        
        return lines.joined(separator: "\n")
    }
    
    // MARK: - Closure Type Signatures
    
    private func closureType(for op: RouteOperation, resource: StripeResource) -> String {
        let returnType = op.returnType ?? resource.swiftTypeName
        
        var paramParts: [String] = []
        
        // Path parameters get labeled underscore params
        for param in op.pathParams {
            paramParts.append("_ \(snakeToCamel(param)): String")
        }
        
        // Multipart file upload operations
        if op.isMultipart {
            paramParts.append("_ fileData: Data")
            paramParts.append("_ fileName: String")
            paramParts.append("_ mimeType: String")
            paramParts.append("_ purpose: String")
        } else if op.hasBody {
            // Request body params struct (for POST operations with body)
            let structName = "\(resource.swiftTypeName)\(op.action)Params"
            if op.hasRequiredBodyFields {
                paramParts.append("_ params: \(structName)")
            } else {
                paramParts.append("_ params: \(structName)?")
            }
        } else {
            // All non-body operations just take expand
            paramParts.append("_ expand: [String]?")
        }
        
        let params = paramParts.isEmpty ? "()" : "(\(paramParts.joined(separator: ", ")))" 
        return "@Sendable \(params) async throws -> \(returnType)"
    }
    
    // MARK: - Live Factory
    
    private func generateLiveFactory(resource: StripeResource, operations: [RouteOperation]) -> [String] {
        var lines: [String] = []
        let returnType = resource.swiftTypeName
        
        lines.append("extension \(resource.swiftTypeName)Routes {")
        lines.append("    static func live(handler: StripeAPIHandler) -> Self {")
        lines.append("        \(resource.swiftTypeName)Routes(")
        
        for (idx, op) in operations.enumerated() {
            let comma = idx < operations.count - 1 ? "," : ""
            let opReturnType = op.returnType ?? returnType
            
            // Build parameter names for the closure
            var closureParams: [String] = []
            for param in op.pathParams {
                closureParams.append(snakeToCamel(param))
            }
            if op.isMultipart {
                closureParams.append(contentsOf: ["fileData", "fileName", "mimeType", "purpose"])
            } else if op.hasBody {
                closureParams.append("params")
            } else {
                closureParams.append("expand")
            }
            
            let closureParamStr = closureParams.isEmpty ? "" : closureParams.joined(separator: ", ")
            
            lines.append("            \(escapedSwiftName(op.funcName)): { \(closureParamStr) in")
            
            // Build path string
            var apiPath = op.path
            for param in op.pathParams {
                apiPath = apiPath.replacingOccurrences(of: "{\(param)}", with: "\\(\(snakeToCamel(param)))")
            }
            
            // Build the handler.send call
            switch op.httpMethod {
            case "POST":
                if op.isMultipart {
                    lines.append("                return try await handler.sendMultipart(")
                    lines.append("                    fileData: fileData,")
                    lines.append("                    fileName: fileName,")
                    lines.append("                    mimeType: mimeType,")
                    lines.append("                    purpose: purpose")
                    lines.append("                ) as \(opReturnType)")
                } else if op.hasBody {
                    if op.hasRequiredBodyFields {
                        lines.append("                let body = params.toFormBody()")
                    } else {
                        lines.append("                let body = params?.toFormBody() ?? \"\"")
                    }
                    lines.append("                return try await handler.send(")
                    lines.append("                    method: .POST,")
                    lines.append("                    path: \"\(apiPath)\",")
                    lines.append("                    body: .bytes(ByteBuffer(string: body))")
                    lines.append("                ) as \(opReturnType)")
                } else {
                    // POST without body
                    lines.append("                var query = \"\"")
                    lines.append("                if let expand { query = expand.map { \"expand[]=\\($0)\" }.joined(separator: \"&\") }")
                    lines.append("                let path = query.isEmpty ? \"\(apiPath)\" : \"\(apiPath)?\\(query)\"")
                    lines.append("                return try await handler.send(")
                    lines.append("                    method: .POST,")
                    lines.append("                    path: path")
                    lines.append("                ) as \(opReturnType)")
                }
                
            case "GET":
                lines.append("                var query = \"\"")
                lines.append("                if let expand { query = expand.map { \"expand[]=\\($0)\" }.joined(separator: \"&\") }")
                lines.append("                let path = query.isEmpty ? \"\(apiPath)\" : \"\(apiPath)?\\(query)\"")
                lines.append("                return try await handler.send(")
                lines.append("                    method: .GET,")
                lines.append("                    path: path")
                lines.append("                ) as \(opReturnType)")
                
            case "DELETE":
                lines.append("                var query = \"\"")
                lines.append("                if let expand { query = expand.map { \"expand[]=\\($0)\" }.joined(separator: \"&\") }")
                lines.append("                let path = query.isEmpty ? \"\(apiPath)\" : \"\(apiPath)?\\(query)\"")
                lines.append("                return try await handler.send(")
                lines.append("                    method: .DELETE,")
                lines.append("                    path: path")
                lines.append("                ) as \(opReturnType)")
                
            default:
                lines.append("                fatalError(\"Unsupported method: \(op.httpMethod)\")")
            }
            
            lines.append("            }\(comma)")
        }
        
        lines.append("        )")
        lines.append("    }")
        lines.append("}")
        
        return lines
    }
    
    // MARK: - Operation Discovery
    
    struct RouteOperation {
        let funcName: String
        let action: String
        let httpMethod: String
        let path: String
        let pathParams: [String]
        let description: String?
        let isDeprecated: Bool
        let hasBody: Bool
        let hasRequiredBodyFields: Bool
        let isListOrSearch: Bool
        let isMultipart: Bool
        let returnType: String?  // nil means use resource type
    }
    
    private func findOperations(for resource: StripeResource) -> [RouteOperation] {
        var results: [RouteOperation] = []
        
        // Deterministic: look up paths directly from the spec-derived mapping
        guard let resourcePaths = pathMapping[resource.schemaName] else { return [] }
        
        // Get unique paths (a path may appear multiple times for list + direct refs)
        let uniquePaths = Set(resourcePaths.map { $0.path })
        
        // Derive basePath: shortest path that is a segment-aligned prefix of at least
        // one other path.  Deterministic — no scoring, no tie-breaking ambiguity.
        let basePath: String = {
            let sorted = uniquePaths.sorted { $0.count < $1.count }
            for candidate in sorted {
                let isPrefix = sorted.contains { other in
                    other != candidate && other.hasPrefix(candidate + "/")
                }
                if isPrefix { return candidate }
            }
            return sorted.first ?? ""
        }()
        
        for path in uniquePaths.sorted() {
            guard let pathItem = spec.paths[path] else { continue }
            
            let methods: [(String, OperationObject?)] = [
                ("GET", pathItem.get),
                ("POST", pathItem.post),
                ("DELETE", pathItem.delete)
            ]
            
            for (method, operation) in methods {
                guard let op = operation else { continue }
                
                let pathParams = extractPathParams(path)
                let (funcName, action) = deriveFuncAndAction(
                    method: method,
                    path: path,
                    pathPrefix: basePath,
                    pathParams: pathParams,
                    operationId: op.operationId
                )
                
                // Check if POST has a requestBody with properties
                let isMultipart = method == "POST" && op.requestBody?.content?["multipart/form-data"] != nil
                let hasBody = method == "POST" && !isMultipart && op.requestBody?.content?["application/x-www-form-urlencoded"]?.schema?.properties?.isEmpty == false
                let requiredFields = op.requestBody?.content?["application/x-www-form-urlencoded"]?.schema?.required ?? []
                
                // Check for list/search patterns
                let isListOrSearch = method == "GET" && (
                    funcName == "list" ||
                    funcName == "search" ||
                    path == basePath  // GET /v1/resources (no path param)
                )
                
                // Determine return type
                let returnType: String?
                if funcName == "list" || (isListOrSearch && !path.contains("search")) {
                    returnType = "\(resource.swiftTypeName)List"
                } else {
                    returnType = nil  // uses resource type
                }
                
                results.append(RouteOperation(
                    funcName: funcName,
                    action: action,
                    httpMethod: method,
                    path: path,
                    pathParams: pathParams,
                    description: op.description,
                    isDeprecated: op.deprecated == true,
                    hasBody: hasBody,
                    hasRequiredBodyFields: !requiredFields.isEmpty,
                    isListOrSearch: isListOrSearch,
                    isMultipart: isMultipart,
                    returnType: returnType
                ))
            }
        }
        
        // Deduplicate by funcName — prefer operations whose path starts with basePath
        // (the resource's own namespace) over cross-resource aliases.
        var bestByFunc: [String: RouteOperation] = [:]
        for op in results {
            if let existing = bestByFunc[op.funcName] {
                let existingIsLocal = existing.path.hasPrefix(basePath)
                let newIsLocal = op.path.hasPrefix(basePath)
                // Replace only if existing is non-local and new is local
                if !existingIsLocal && newIsLocal {
                    bestByFunc[op.funcName] = op
                }
            } else {
                bestByFunc[op.funcName] = op
            }
        }
        results = Array(bestByFunc.values)
        
        return results.sorted { a, b in
            // Sort by: create, retrieve, update, list, delete, then alphabetical
            let order = ["create": 0, "retrieve": 1, "update": 2, "list": 3, "search": 4, "delete": 5]
            let aOrder = order[a.funcName] ?? 10
            let bOrder = order[b.funcName] ?? 10
            if aOrder != bOrder { return aOrder < bOrder }
            return a.funcName < b.funcName
        }
    }
    
    private func deriveFuncAndAction(
        method: String,
        path: String,
        pathPrefix: String,
        pathParams: [String],
        operationId: String?
    ) -> (funcName: String, action: String) {
        // Use operationId from the spec — it's the canonical source of truth.
        // Pattern: {Method}{PascalSegments}
        //   GetRefunds           → list
        //   PostRefunds          → create
        //   GetRefundsRefund     → retrieve
        //   PostRefundsRefund    → update
        //   DeleteRefundsRefund  → delete
        //   GetCustomersSearch   → search
        //   PostRefundsRefundCancel → cancel
        //   PostAccountsAccountReject → reject
        
        guard let _ = operationId else {
            return ("unknown", "Unknown")
        }
        
        // Use the path structure relative to basePath to classify the operation.
        // The basePath is scored as the path that is a segment-aligned prefix of the most other paths.
        let pathSegments = path.split(separator: "/")
            .filter { $0 != "v1" }
            .map { String($0) }
        
        switch method {
        case "DELETE":
            return ("delete", "Delete")
            
        case "GET":
            // GET with no path params beyond basePath → list
            // GET {basePath}/{id} → retrieve  
            // GET {basePath}/search → search
            
            // Check if this is a search endpoint
            if path.hasSuffix("/search") {
                return ("search", "Search")
            }
            
            // If path has more segments than basePath params, check for sub-actions
            let nonParamSegments = pathSegments.filter { !$0.hasPrefix("{") }
            let basePrefixSegments = pathPrefix.split(separator: "/").filter { $0 != "v1" }.map(String.init).filter { !$0.hasPrefix("{") }
            let extraNonParams = nonParamSegments.count - basePrefixSegments.count
            
            if extraNonParams > 0 {
                // Has extra non-param segments beyond basePath — named sub-resource or action
                if let lastSeg = nonParamSegments.last, !basePrefixSegments.contains(lastSeg) {
                    let camelAction = snakeToCamel(lastSeg)
                    return ("list\(capitalize(camelAction))", "List\(capitalize(camelAction))")
                }
            }
            
            // GET with path param after basePath → retrieve
            // GET basePath (no extra segments) → list
            if pathParams.count > pathPrefix.split(separator: "/").filter({ $0.hasPrefix("{") }).count {
                return ("retrieve", "Retrieve")
            }
            
            return ("list", "List")
            
        case "POST":
            let basePrefixParamCount = pathPrefix.split(separator: "/").filter { $0.hasPrefix("{") }.count
            let totalPathParams = pathParams.count
            
            // POST basePath (no path params beyond prefix) → create
            if totalPathParams == basePrefixParamCount && path == pathPrefix {
                return ("create", "Create")
            }
            
            // POST basePath/{id} (one extra path param, no trailing action) → update
            let trailingParts = path.hasPrefix(pathPrefix) ? String(path.dropFirst(pathPrefix.count)) : ""
            let trailingNonParams = trailingParts.split(separator: "/").filter { !$0.hasPrefix("{") }
            
            if trailingNonParams.isEmpty && totalPathParams == basePrefixParamCount + 1 {
                return ("update", "Update")
            }
            
            // POST with trailing action segment → named action
            if let actionSlug = trailingNonParams.last {
                let camelAction = snakeToCamel(String(actionSlug))
                return (camelAction, capitalize(camelAction))
            }
            
            return ("create", "Create")
            
        default:
            return (snakeToCamel(operationId ?? "unknown"), capitalize(snakeToCamel(operationId ?? "Unknown")))
        }
    }
    
    // MARK: - Helpers
    
    private func extractPathParams(_ path: String) -> [String] {
        var params: [String] = []
        var remaining = path[...]
        while let start = remaining.firstIndex(of: "{"),
              let end = remaining.firstIndex(of: "}") {
            let param = String(remaining[remaining.index(after: start)..<end])
            params.append(param)
            remaining = remaining[remaining.index(after: end)...]
        }
        return params
    }
    
}