//
//  Helpers.swift
//  StripeKit
//
//  Generated by stripe-kit-codegen
//

import Foundation

extension Dictionary where Key == String, Value == Any {
    /// Encode a dictionary of parameters into a URL query string.
    var queryParameters: String {
        flatMap { flatten(key: $0.key, value: $0.value) }
            .map { "\($0.0)=\($0.1.addingPercentEncoding(withAllowedCharacters: .stripeQueryAllowed) ?? $0.1)" }
            .joined(separator: "&")
    }

    private func flatten(key: String, value: Any) -> [(String, String)] {
        switch value {
        case let dict as [String: Any]:
            return dict.flatMap { flatten(key: "\(key)[\($0.key)]", value: $0.value) }
        case let array as [Any]:
            return array.enumerated().flatMap { flatten(key: "\(key)[\($0.offset)]", value: $0.element) }
        case let b as Bool:
            return [(key, b ? "true" : "false")]
        default:
            return [(key, "\(value)")]
        }
    }
}

extension CharacterSet {
    /// URL query allowed characters minus `+`, `&`, and `=` which have special
    /// meaning in form-encoded bodies.
    static let stripeQueryAllowed: CharacterSet = {
        var cs = CharacterSet.urlQueryAllowed
        cs.remove("+")
        cs.remove("&")
        cs.remove("=")
        return cs
    }()
}
