//
//  StripeParams.swift
//  StripeKit
//
//  Generated by stripe-kit-codegen
//

import Foundation

/// Protocol for typed API parameter structs.
/// Conforming types automatically get form-encoded body generation.
public protocol StripeParams: Codable, Sendable {
    /// Convert this params struct to a URL-encoded form body string.
    func toFormBody() -> String
}

extension StripeParams {
    public func toFormBody() -> String {
        var pairs: [(String, String)] = []
        encodeFields(of: self, prefix: "", into: &pairs)
        return pairs
            .map { "\($0.0)=\($0.1.addingPercentEncoding(withAllowedCharacters: .stripeQueryAllowed) ?? $0.1)" }
            .joined(separator: "&")
    }

    private func encodeFields(of value: Any, prefix: String, into pairs: inout [(String, String)]) {
        let mirror = Mirror(reflecting: value)

        for child in mirror.children {
            guard let label = child.label else { continue }
            let key = prefix.isEmpty ? camelToSnake(label) : "\(prefix)[\(camelToSnake(label))]"

            // Skip nil optionals
            let valueMirror = Mirror(reflecting: child.value)
            if valueMirror.displayStyle == .optional && valueMirror.children.isEmpty { continue }

            // Unwrap optional
            let unwrapped: Any
            if valueMirror.displayStyle == .optional, let (_, some) = valueMirror.children.first {
                unwrapped = some
            } else {
                unwrapped = child.value
            }

            encodeSingleValue(unwrapped, key: key, into: &pairs)
        }
    }

    private func encodeSingleValue(_ value: Any, key: String, into pairs: inout [(String, String)]) {
        switch value {
        case let b as Bool:
            pairs.append((key, b ? "true" : "false"))
        case let n as any Numeric:
            pairs.append((key, "\(n)"))
        case let s as String:
            pairs.append((key, s))
        case let dict as [String: String]:
            // Stripe bracket notation: metadata[key]=value
            for (k, v) in dict.sorted(by: { $0.key < $1.key }) {
                pairs.append(("\(key)[\(k)]", v))
            }
        case let arr as [String]:
            // Stripe array notation: expand[]=value
            for item in arr {
                pairs.append(("\(key)[]", item))
            }
        case let nested as any StripeParams:
            // Recurse into sub-structs: parent[child_field]=value
            encodeFields(of: nested, prefix: key, into: &pairs)
        default:
            // Handles RawRepresentable enums and other types
            let m = Mirror(reflecting: value)
            if let rawChild = m.children.first(where: { $0.label == "rawValue" }) {
                pairs.append((key, "\(rawChild.value)"))
            } else {
                pairs.append((key, "\(value)"))
            }
        }
    }

    private func camelToSnake(_ input: String) -> String {
        var result = ""
        for char in input {
            if char.isUppercase {
                result += "_"
                result += char.lowercased()
            } else {
                result += String(char)
            }
        }
        return result
    }
}
