//
//  StripeError.swift
//  StripeKit
//
//  Generated by stripe-kit-codegen
//

import Foundation

/// A Stripe API error, suitable for typed `throws(StripeError)`.
public struct StripeError: Swift.Error, Codable, Sendable {
    public var error: StripeAPIError?
}

/// Detailed error information from the Stripe API.
public struct StripeAPIError: Codable, Sendable {
    /// The type of error returned.
    public var type: StripeErrorType?
    /// For card errors, the ID of the failed charge.
    public var charge: String?
    /// A short string indicating the error code reported.
    public var code: StripeErrorCode?
    /// A short string for the card issuer's decline reason.
    public var declineCode: StripeDeclineCode?
    /// A URL to more information about the error code.
    public var docUrl: String?
    /// A human-readable message providing more details.
    public var message: String?
    /// The parameter related to the error, if applicable.
    public var param: String?

    public enum CodingKeys: String, CodingKey {
        case type, charge, code, message, param
        case declineCode = "decline_code"
        case docUrl = "doc_url"
    }
}

public enum StripeErrorType: String, Codable, Sendable {
    case apiError = "api_error"
    case cardError = "card_error"
    case idempotencyError = "idempotency_error"
    case invalidRequestError = "invalid_request_error"
}

public enum StripeErrorCode: String, Codable, Sendable {
    case accountClosed = "account_closed"
    case accountCountryInvalidAddress = "account_country_invalid_address"
    case accountErrorCountryChangeRequiresAdditionalSteps = "account_error_country_change_requires_additional_steps"
    case accountInformationMismatch = "account_information_mismatch"
    case accountInvalid = "account_invalid"
    case accountNumberInvalid = "account_number_invalid"
    case accountTokenRequiredForV2Account = "account_token_required_for_v2_account"
    case acssDebitSessionIncomplete = "acss_debit_session_incomplete"
    case alipayUpgradeRequired = "alipay_upgrade_required"
    case amountTooLarge = "amount_too_large"
    case amountTooSmall = "amount_too_small"
    case apiKeyExpired = "api_key_expired"
    case applicationFeesNotAllowed = "application_fees_not_allowed"
    case authenticationRequired = "authentication_required"
    case balanceInsufficient = "balance_insufficient"
    case balanceInvalidParameter = "balance_invalid_parameter"
    case bankAccountBadRoutingNumbers = "bank_account_bad_routing_numbers"
    case bankAccountDeclined = "bank_account_declined"
    case bankAccountExists = "bank_account_exists"
    case bankAccountRestricted = "bank_account_restricted"
    case bankAccountUnusable = "bank_account_unusable"
    case bankAccountUnverified = "bank_account_unverified"
    case bankAccountVerificationFailed = "bank_account_verification_failed"
    case billingInvalidMandate = "billing_invalid_mandate"
    case bitcoinUpgradeRequired = "bitcoin_upgrade_required"
    case captureChargeAuthorizationExpired = "capture_charge_authorization_expired"
    case captureUnauthorizedPayment = "capture_unauthorized_payment"
    case cardDeclineRateLimitExceeded = "card_decline_rate_limit_exceeded"
    case cardDeclined = "card_declined"
    case cardholderPhoneNumberRequired = "cardholder_phone_number_required"
    case chargeAlreadyCaptured = "charge_already_captured"
    case chargeAlreadyRefunded = "charge_already_refunded"
    case chargeDisputed = "charge_disputed"
    case chargeExceedsSourceLimit = "charge_exceeds_source_limit"
    case chargeExceedsTransactionLimit = "charge_exceeds_transaction_limit"
    case chargeExpiredForCapture = "charge_expired_for_capture"
    case chargeInvalidParameter = "charge_invalid_parameter"
    case chargeNotRefundable = "charge_not_refundable"
    case clearingCodeUnsupported = "clearing_code_unsupported"
    case countryCodeInvalid = "country_code_invalid"
    case countryUnsupported = "country_unsupported"
    case couponExpired = "coupon_expired"
    case customerMaxPaymentMethods = "customer_max_payment_methods"
    case customerMaxSubscriptions = "customer_max_subscriptions"
    case customerSessionExpired = "customer_session_expired"
    case customerTaxLocationInvalid = "customer_tax_location_invalid"
    case debitNotAuthorized = "debit_not_authorized"
    case emailInvalid = "email_invalid"
    case expiredCard = "expired_card"
    case financialConnectionsAccountInactive = "financial_connections_account_inactive"
    case financialConnectionsAccountPendingAccountNumbers = "financial_connections_account_pending_account_numbers"
    case financialConnectionsAccountUnavailableAccountNumbers = "financial_connections_account_unavailable_account_numbers"
    case financialConnectionsNoSuccessfulTransactionRefresh = "financial_connections_no_successful_transaction_refresh"
    case forwardingApiInactive = "forwarding_api_inactive"
    case forwardingApiInvalidParameter = "forwarding_api_invalid_parameter"
    case forwardingApiRetryableUpstreamError = "forwarding_api_retryable_upstream_error"
    case forwardingApiUpstreamConnectionError = "forwarding_api_upstream_connection_error"
    case forwardingApiUpstreamConnectionTimeout = "forwarding_api_upstream_connection_timeout"
    case forwardingApiUpstreamError = "forwarding_api_upstream_error"
    case idempotencyKeyInUse = "idempotency_key_in_use"
    case incorrectAddress = "incorrect_address"
    case incorrectCvc = "incorrect_cvc"
    case incorrectNumber = "incorrect_number"
    case incorrectZip = "incorrect_zip"
    case indiaRecurringPaymentMandateCanceled = "india_recurring_payment_mandate_canceled"
    case instantPayoutsConfigDisabled = "instant_payouts_config_disabled"
    case instantPayoutsCurrencyDisabled = "instant_payouts_currency_disabled"
    case instantPayoutsLimitExceeded = "instant_payouts_limit_exceeded"
    case instantPayoutsUnsupported = "instant_payouts_unsupported"
    case insufficientFunds = "insufficient_funds"
    case intentInvalidState = "intent_invalid_state"
    case intentVerificationMethodMissing = "intent_verification_method_missing"
    case invalidCardType = "invalid_card_type"
    case invalidCharacters = "invalid_characters"
    case invalidChargeAmount = "invalid_charge_amount"
    case invalidCvc = "invalid_cvc"
    case invalidExpiryMonth = "invalid_expiry_month"
    case invalidExpiryYear = "invalid_expiry_year"
    case invalidMandateReferencePrefixFormat = "invalid_mandate_reference_prefix_format"
    case invalidNumber = "invalid_number"
    case invalidSourceUsage = "invalid_source_usage"
    case invalidTaxLocation = "invalid_tax_location"
    case invoiceNoCustomerLineItems = "invoice_no_customer_line_items"
    case invoiceNoPaymentMethodTypes = "invoice_no_payment_method_types"
    case invoiceNoSubscriptionLineItems = "invoice_no_subscription_line_items"
    case invoiceNotEditable = "invoice_not_editable"
    case invoiceOnBehalfOfNotEditable = "invoice_on_behalf_of_not_editable"
    case invoicePaymentIntentRequiresAction = "invoice_payment_intent_requires_action"
    case invoiceUpcomingNone = "invoice_upcoming_none"
    case livemodeMismatch = "livemode_mismatch"
    case lockTimeout = "lock_timeout"
    case missing
    case noAccount = "no_account"
    case notAllowedOnStandardAccount = "not_allowed_on_standard_account"
    case outOfInventory = "out_of_inventory"
    case ownershipDeclarationNotAllowed = "ownership_declaration_not_allowed"
    case parameterInvalidEmpty = "parameter_invalid_empty"
    case parameterInvalidInteger = "parameter_invalid_integer"
    case parameterInvalidStringBlank = "parameter_invalid_string_blank"
    case parameterInvalidStringEmpty = "parameter_invalid_string_empty"
    case parameterMissing = "parameter_missing"
    case parameterUnknown = "parameter_unknown"
    case parametersExclusive = "parameters_exclusive"
    case paymentIntentActionRequired = "payment_intent_action_required"
    case paymentIntentAuthenticationFailure = "payment_intent_authentication_failure"
    case paymentIntentIncompatiblePaymentMethod = "payment_intent_incompatible_payment_method"
    case paymentIntentInvalidParameter = "payment_intent_invalid_parameter"
    case paymentIntentKonbiniRejectedConfirmationNumber = "payment_intent_konbini_rejected_confirmation_number"
    case paymentIntentMandateInvalid = "payment_intent_mandate_invalid"
    case paymentIntentPaymentAttemptExpired = "payment_intent_payment_attempt_expired"
    case paymentIntentPaymentAttemptFailed = "payment_intent_payment_attempt_failed"
    case paymentIntentRateLimitExceeded = "payment_intent_rate_limit_exceeded"
    case paymentIntentUnexpectedState = "payment_intent_unexpected_state"
    case paymentMethodBankAccountAlreadyVerified = "payment_method_bank_account_already_verified"
    case paymentMethodBankAccountBlocked = "payment_method_bank_account_blocked"
    case paymentMethodBillingDetailsAddressMissing = "payment_method_billing_details_address_missing"
    case paymentMethodConfigurationFailures = "payment_method_configuration_failures"
    case paymentMethodCurrencyMismatch = "payment_method_currency_mismatch"
    case paymentMethodCustomerDecline = "payment_method_customer_decline"
    case paymentMethodInvalidParameter = "payment_method_invalid_parameter"
    case paymentMethodInvalidParameterTestmode = "payment_method_invalid_parameter_testmode"
    case paymentMethodMicrodepositFailed = "payment_method_microdeposit_failed"
    case paymentMethodMicrodepositVerificationAmountsInvalid = "payment_method_microdeposit_verification_amounts_invalid"
    case paymentMethodMicrodepositVerificationAmountsMismatch = "payment_method_microdeposit_verification_amounts_mismatch"
    case paymentMethodMicrodepositVerificationAttemptsExceeded = "payment_method_microdeposit_verification_attempts_exceeded"
    case paymentMethodMicrodepositVerificationDescriptorCodeMismatch = "payment_method_microdeposit_verification_descriptor_code_mismatch"
    case paymentMethodMicrodepositVerificationTimeout = "payment_method_microdeposit_verification_timeout"
    case paymentMethodNotAvailable = "payment_method_not_available"
    case paymentMethodProviderDecline = "payment_method_provider_decline"
    case paymentMethodProviderTimeout = "payment_method_provider_timeout"
    case paymentMethodUnactivated = "payment_method_unactivated"
    case paymentMethodUnexpectedState = "payment_method_unexpected_state"
    case paymentMethodUnsupportedType = "payment_method_unsupported_type"
    case payoutReconciliationNotReady = "payout_reconciliation_not_ready"
    case payoutsLimitExceeded = "payouts_limit_exceeded"
    case payoutsNotAllowed = "payouts_not_allowed"
    case platformAccountRequired = "platform_account_required"
    case platformApiKeyExpired = "platform_api_key_expired"
    case postalCodeInvalid = "postal_code_invalid"
    case processingError = "processing_error"
    case productInactive = "product_inactive"
    case progressiveOnboardingLimitExceeded = "progressive_onboarding_limit_exceeded"
    case rateLimit = "rate_limit"
    case referToCustomer = "refer_to_customer"
    case refundDisputedPayment = "refund_disputed_payment"
    case requestBlocked = "request_blocked"
    case resourceAlreadyExists = "resource_already_exists"
    case resourceMissing = "resource_missing"
    case returnIntentAlreadyProcessed = "return_intent_already_processed"
    case routingNumberInvalid = "routing_number_invalid"
    case secretKeyRequired = "secret_key_required"
    case sepaUnsupportedAccount = "sepa_unsupported_account"
    case setupAttemptFailed = "setup_attempt_failed"
    case setupIntentAuthenticationFailure = "setup_intent_authentication_failure"
    case setupIntentInvalidParameter = "setup_intent_invalid_parameter"
    case setupIntentMandateInvalid = "setup_intent_mandate_invalid"
    case setupIntentMobileWalletUnsupported = "setup_intent_mobile_wallet_unsupported"
    case setupIntentSetupAttemptExpired = "setup_intent_setup_attempt_expired"
    case setupIntentUnexpectedState = "setup_intent_unexpected_state"
    case shippingAddressInvalid = "shipping_address_invalid"
    case shippingCalculationFailed = "shipping_calculation_failed"
    case skuInactive = "sku_inactive"
    case stateUnsupported = "state_unsupported"
    case statusTransitionInvalid = "status_transition_invalid"
    case stripeTaxInactive = "stripe_tax_inactive"
    case taxIdInvalid = "tax_id_invalid"
    case taxIdProhibited = "tax_id_prohibited"
    case taxesCalculationFailed = "taxes_calculation_failed"
    case terminalLocationCountryUnsupported = "terminal_location_country_unsupported"
    case terminalReaderBusy = "terminal_reader_busy"
    case terminalReaderHardwareFault = "terminal_reader_hardware_fault"
    case terminalReaderInvalidLocationForActivation = "terminal_reader_invalid_location_for_activation"
    case terminalReaderInvalidLocationForPayment = "terminal_reader_invalid_location_for_payment"
    case terminalReaderOffline = "terminal_reader_offline"
    case terminalReaderTimeout = "terminal_reader_timeout"
    case testmodeChargesOnly = "testmode_charges_only"
    case tlsVersionUnsupported = "tls_version_unsupported"
    case tokenAlreadyUsed = "token_already_used"
    case tokenCardNetworkInvalid = "token_card_network_invalid"
    case tokenInUse = "token_in_use"
    case transferSourceBalanceParametersMismatch = "transfer_source_balance_parameters_mismatch"
    case transfersNotAllowed = "transfers_not_allowed"
    case urlInvalid = "url_invalid"
}

public typealias StripeDeclineCode = String

/// Errors during webhook signature verification.
public enum StripeSignatureError: Swift.Error, Sendable {
    case unableToParseHeader
    case noMatchingSignatureFound
    case timestampNotTolerated
}
