//
//  StripeEvent.swift
//  StripeKit
//
//  Generated by stripe-kit-codegen
//

import Foundation
import Crypto

/// A Stripe webhook event with typed object extraction.
public struct StripeEvent: Codable, Sendable {
    public var id: String
    public var object: String
    public var apiVersion: String?
    public var created: Date
    public var data: EventData
    public var livemode: Bool
    public var pendingWebhooks: Int
    public var request: EventRequest?
    public var type: String

    public enum CodingKeys: String, CodingKey {
        case id, object, created, data, livemode, type
        case apiVersion = "api_version"
        case pendingWebhooks = "pending_webhooks"
        case request
    }
}

public struct EventData: Codable, Sendable {
    /// The raw JSON object. Use `object(as:)` for typed access.
    public var _object: AnyCodableValue?
    /// The raw JSON previous attributes. Use `previousAttributes(as:)` for typed access.
    public var _previousAttributes: AnyCodableValue?

    public enum CodingKeys: String, CodingKey {
        case _object = "object"
        case _previousAttributes = "previous_attributes"
    }

    /// Decode the event's object as a typed Stripe resource.
    public func object<T: Codable>(as type: T.Type) throws -> T {
        let data = try JSONSerialization.data(withJSONObject: _object?.value ?? [:] as [String: Any])
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .secondsSince1970
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        return try decoder.decode(T.self, from: data)
    }

    /// Decode the event's previous attributes as a Stripe resource.
    /// Only changed fields are present — non-optional model fields that were
    /// unchanged will decode as nil since they aren't in the JSON.
    public func previousAttributes<T: Codable>(as type: T.Type) throws -> T? {
        guard let prev = _previousAttributes?.value else { return nil }
        let data = try JSONSerialization.data(withJSONObject: prev)
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .secondsSince1970
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        return try decoder.decode(T.self, from: data)
    }
}

public struct EventRequest: Codable, Sendable {
    public var id: String?
    public var idempotencyKey: String?

    public enum CodingKeys: String, CodingKey {
        case id
        case idempotencyKey = "idempotency_key"
    }
}

// MARK: - Signature Verification

extension StripeEvent {
    /// Verify a webhook signature and decode the event.
    /// - Parameters:
    ///   - payload: The raw request body bytes
    ///   - header: The Stripe-Signature header value
    ///   - secret: Your webhook endpoint secret (whsec_...)
    ///   - tolerance: Maximum age in seconds (default: 300)
    /// - Returns: The decoded and verified StripeEvent
    public static func verify(
        payload: Data,
        header: String,
        secret: String,
        tolerance: Double = 300
    ) throws -> StripeEvent {
        try verifySignature(payload: payload, header: header, secret: secret, tolerance: tolerance)

        // Decode the event
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .secondsSince1970
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        return try decoder.decode(StripeEvent.self, from: payload)
    }

    /// Verify a webhook signature without decoding the event.
    /// Throws if the signature is invalid, the header is malformed, or the timestamp is too old.
    public static func verifySignature(
        payload: Data,
        header: String,
        secret: String,
        tolerance: Double = 300
    ) throws {
        // Parse header: t=timestamp,v1=sig1,v1=sig2,...
        let pairs = header.split(separator: ",").reduce(into: [String: [String]]()) { result, pair in
            let kv = pair.split(separator: "=", maxSplits: 1)
            guard kv.count == 2 else { return }
            result[String(kv[0]), default: []].append(String(kv[1]))
        }

        guard let timestamps = pairs["t"], let timestamp = timestamps.first,
              let signatures = pairs["v1"], !signatures.isEmpty
        else { throw StripeSignatureError.unableToParseHeader }

        // Compute expected signature
        let signedPayload = "\(timestamp).\(String(data: payload, encoding: .utf8) ?? "")"
        let secretKey = SymmetricKey(data: Data(secret.utf8))
        let signature = HMAC<SHA256>.authenticationCode(for: Data(signedPayload.utf8), using: secretKey)
        let expected = signature.map { String(format: "%02x", $0) }.joined()

        // Check for a matching signature
        guard signatures.contains(where: { $0 == expected }) else {
            throw StripeSignatureError.noMatchingSignatureFound
        }

        // Verify timestamp tolerance
        if let ts = Double(timestamp) {
            let age = Date().timeIntervalSince1970 - ts
            guard abs(age) <= tolerance else {
                throw StripeSignatureError.timestampNotTolerated
            }
        }
    }
}

// MARK: - AnyCodableValue

/// A type-erased Codable value for preserving raw JSON in webhook events.
public struct AnyCodableValue: Codable, @unchecked Sendable {
    public let value: Any

    public init(_ value: Any) {
        self.value = value
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            value = Optional<Any>.none as Any
        } else if let dict = try? container.decode([String: AnyCodableValue].self) {
            value = dict.mapValues { $0.value }
        } else if let array = try? container.decode([AnyCodableValue].self) {
            value = array.map { $0.value }
        } else if let string = try? container.decode(String.self) {
            value = string
        } else if let int = try? container.decode(Int.self) {
            value = int
        } else if let double = try? container.decode(Double.self) {
            value = double
        } else if let bool = try? container.decode(Bool.self) {
            value = bool
        } else {
            value = Optional<Any>.none as Any
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch value {
        case let v as String: try container.encode(v)
        case let v as Int: try container.encode(v)
        case let v as Double: try container.encode(v)
        case let v as Bool: try container.encode(v)
        case let v as [Any]: try container.encode(v.map { AnyCodableValue($0) })
        case let v as [String: Any]: try container.encode(v.mapValues { AnyCodableValue($0) })
        default: try container.encodeNil()
        }
    }
}
