//
//  StripeParams.swift
//  StripeKit
//
//  Generated by stripe-kit-codegen
//

import Foundation

/// Protocol for typed API parameter structs.
/// Conforming types automatically get form-encoded body generation.
public protocol StripeParams: Codable, Sendable {
    /// Convert this params struct to a URL-encoded form body string.
    func toFormBody() -> String
}

extension StripeParams {
    public func toFormBody() -> String {
        var pairs: [(String, String)] = []
        let mirror = Mirror(reflecting: self)
        
        for child in mirror.children {
            guard let label = child.label else { continue }
            // Convert camelCase property name to snake_case
            let key = camelToSnake(label)
            
            // Skip nil optionals
            let valueMirror = Mirror(reflecting: child.value)
            if valueMirror.displayStyle == .optional && valueMirror.children.isEmpty { continue }
            
            // Unwrap optional
            let unwrapped: Any
            if valueMirror.displayStyle == .optional, let (_, some) = valueMirror.children.first {
                unwrapped = some
            } else {
                unwrapped = child.value
            }
            
            // Encode value preserving Bool as true/false
            switch unwrapped {
            case let b as Bool:
                pairs.append((key, b ? "true" : "false"))
            case let n as any Numeric:
                pairs.append((key, "\(n)"))
            case let s as String:
                pairs.append((key, s))
            default:
                pairs.append((key, "\(unwrapped)"))
            }
        }
        
        return pairs
            .map { "\($0.0)=\($0.1.addingPercentEncoding(withAllowedCharacters: .stripeQueryAllowed) ?? $0.1)" }
            .joined(separator: "&")
    }
    
    private func camelToSnake(_ input: String) -> String {
        var result = ""
        for char in input {
            if char.isUppercase {
                result += "_"
                result += char.lowercased()
            } else {
                result += String(char)
            }
        }
        return result
    }
}
