//
//  ReaderRoutes.swift
//  StripeKit
//
//  Created by Andrew Edwards on 6/1/19.
//

import NIO
import NIOHTTP1

public protocol ReaderRoutes {
    /// Creates a new Reader object.
    ///
    /// - Parameters:
    ///   - registrationCode: A code generated by the reader used for registering to an account.
    ///   - label: Custom label given to the reader for easier identification. If no label is specified, the registration code will be used.
    ///   - location: The location to assign the reader to. If no location is specified, the reader will be assigned to the account’s default location.
    ///   - metadata: Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    /// - Returns: A `StripeReader`.
    func create(registrationCode: String, label: String?, location: String?, metadata: [String: String]?) -> EventLoopFuture<StripeReader>
    
    /// Retrieves a Reader object.
    ///
    /// - Parameter reader: The identifier of the reader to be retrieved.
    /// - Returns: A `StripeReader`.
    func retrieve(reader: String) -> EventLoopFuture<StripeReader>
    
    /// Updates a Reader object by setting the values of the parameters passed. Any parameters not provided will be left unchanged.
    ///
    /// - Parameters:
    ///   - reader: The identifier of the reader to be updated.
    ///   - label: The new label of the reader.
    ///   - metadata: Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
    /// - Returns: A `StripeReader`.
    func update(reader: String, label: String?, metadata: [String: String]?) -> EventLoopFuture<StripeReader>
    
    /// Deletes a Reader object.
    ///
    /// - Parameter reader: The identifier of the reader to be deleted.
    /// - Returns: A `StripeReader`.
    func delete(reader: String) -> EventLoopFuture<StripeReader>
    
    /// Returns a list of Reader objects.
    ///
    /// - Parameter filter: A dictionary that will be used for the query parameters. [See More →](https://stripe.com/docs/api/terminal/readers/list)
    /// - Returns: A `StripeReaderList`.
    func listAll(filter: [String: Any]?) -> EventLoopFuture<StripeReaderList>
    
    /// Headers to send with the request.
    var headers: HTTPHeaders { get set }
}

extension ReaderRoutes {
    func create(registrationCode: String, label: String? = nil, location: String? = nil, metadata: [String: String]? = nil) -> EventLoopFuture<StripeReader> {
        return create(registrationCode: registrationCode, label: label, location: location, metadata: metadata)
    }
    
    func retrieve(reader: String) -> EventLoopFuture<StripeReader> {
        return retrieve(reader: reader)
    }
    
    func update(reader: String, label: String? = nil, metadata: [String: String]? = nil) -> EventLoopFuture<StripeReader> {
        return update(reader: reader, label: label, metadata: metadata)
    }
    
    func delete(reader: String) -> EventLoopFuture<StripeReader> {
        return delete(reader: reader)
    }
    
    func listAll(filter: [String: Any]? = nil) -> EventLoopFuture<StripeReaderList> {
        return listAll(filter: filter)
    }
}

public struct StripeReaderRoutes: ReaderRoutes {
    public var headers: HTTPHeaders = [:]
    
    private let apiHandler: StripeAPIHandler
    private let terminalreaders = APIBase + APIVersion + "terminal/readers"
    
    init(apiHandler: StripeAPIHandler) {
        self.apiHandler = apiHandler
    }
    
    public func create(registrationCode: String, label: String?, location: String?, metadata: [String: String]?) -> EventLoopFuture<StripeReader> {
        var body: [String: Any] = ["registration_code": registrationCode]
        
        if let label = label {
            body["label"] = label
        }
        
        if let location = location {
            body["location"] = location
        }
        
        if let metadata = metadata {
            metadata.forEach { body["metadata[\($0)]"] = $1 }
        }
        
        return apiHandler.send(method: .POST, path: terminalreaders, body: .string(body.queryParameters), headers: headers)
    }
    
    public func retrieve(reader: String) -> EventLoopFuture<StripeReader> {
        return apiHandler.send(method: .GET, path: "\(terminalreaders)/\(reader)", headers: headers)
    }
    
    public func update(reader: String, label: String?, metadata: [String: String]?) -> EventLoopFuture<StripeReader> {
        var body: [String: Any] = [:]
        
        if let label = label {
            body["label"] = label
        }
        
        if let metadata = metadata {
            metadata.forEach { body["metadata[\($0)]"] = $1 }
        }
        
        return apiHandler.send(method: .POST, path: "\(terminalreaders)/\(reader)", body: .string(body.queryParameters), headers: headers)
    }
    
    public func delete(reader: String) -> EventLoopFuture<StripeReader> {
        return apiHandler.send(method: .DELETE, path: "\(terminalreaders)/\(reader)", headers: headers)
    }
    
    public func listAll(filter: [String: Any]?) -> EventLoopFuture<StripeReaderList> {
        var queryParams = ""
        if let filter = filter {
            queryParams = filter.queryParameters
        }
        
        return apiHandler.send(method: .GET, path: terminalreaders, query: queryParams, headers: headers)
    }
}
